// ============================================================================
// AI Workforce Module — Pluggable LLM Interface
// ============================================================================
// The AI Workforce can run with multiple LLM backends:
//
//   1. StubLLM     — rule-based responses, requires NO API key. Used for testing
//                    and for orgs that haven't configured an LLM provider yet.
//                    Every agent returns a deterministic, contextual response.
//
//   2. GeminiLLM   — uses @google/generative-ai (Google Gemini). Activated when
//                    GEMINI_API_KEY (or GOOGLE_API_KEY) is set in env.
//                    Models default to gemini-2.0-flash-001 (override with
//                    GEMINI_MODEL env var). Falls back to StubLLM on any error.
//
//   3. ZaiLLM      — uses z-ai-web-dev-sdk (the same SDK used by other Valtriox
//                    AI features). Activated when ZAI_API_KEY is set in env.
//                    Falls back to StubLLM on any error.
//
// Provider priority: Gemini > Z.ai > Stub
//
// To add a new provider (OpenAI, Anthropic, etc.), implement the LLMProvider
// interface and add a branch in getLLMProvider().
// ============================================================================

import logger from "@/lib/logger";

export interface LLMMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

export interface LLMRequest {
  messages: LLMMessage[];
  // Lower temperature = more deterministic. Agents should use 0.3-0.5.
  temperature?: number;
  // Max tokens for the response
  maxTokens?: number;
  // Optional: response format hint (e.g., "json" for structured output)
  responseFormat?: "text" | "json";
}

export interface LLMResponse {
  content: string;
  // Whether the response was generated by a real LLM or fell back to stub
  powered: boolean;
  // Tokens used (only set by real LLM)
  tokensUsed?: number;
  // Latency in ms
  latencyMs: number;
  // Display name of the active provider (for dashboard UI)
  provider: string;
  // If the real LLM failed and fell back to stub, the error message.
  // Useful for debugging — surfaced in the UI and health check endpoint.
  lastError?: string;
}

export interface LLMProvider {
  name: string;
  isAvailable: boolean;
  generate(req: LLMRequest): Promise<LLMResponse>;
}

// ────────────────────────────────────────────────────────────────────────────
// Stub LLM — rule-based, deterministic, no API key required
// ────────────────────────────────────────────────────────────────────────────

class StubLLM implements LLMProvider {
  name = "stub";
  isAvailable = true;

  async generate(req: LLMRequest): Promise<LLMResponse> {
    const start = Date.now();
    const lastUser = [...req.messages].reverse().find((m) => m.role === "user");
    const userContent = lastUser?.content || "";
    const systemMsg = req.messages.find((m) => m.role === "system")?.content || "";

    // Extract agent name from system prompt
    const agentNameMatch = systemMsg.match(/You are the (.*?) agent/i);
    const agentName = agentNameMatch ? agentNameMatch[1] : "AI";

    // Detect intent from the query
    const lower = userContent.toLowerCase();
    let response: string;

    if (lower.includes("summary") || lower.includes("brief") || lower.includes("status")) {
      response = `**${agentName} Agent — Stub Mode Report**\n\nI'm operating in stub mode (no LLM API key configured). Here's what I'd normally do:\n\n1. Retrieve relevant memory entries from the knowledge store\n2. Query the live business database for current metrics\n3. Synthesize a ${agentName.toLowerCase()}-focused summary\n4. Recommend 2-3 actions for your review\n\nTo enable real AI responses, set the GEMINI_API_KEY environment variable in your Vercel project settings. Once set, I'll provide intelligent, context-aware responses.\n\nIn the meantime, all my workflows, tasks, and message-bus communications are fully functional — only the natural-language reasoning is stubbed.`;
    } else if (lower.includes("revenue") || lower.includes("finance") || lower.includes("money")) {
      response = `**${agentName} Agent — Financial Stub Response**\n\nTo provide real revenue insights, I need:\n- A connected LLM provider (set GEMINI_API_KEY)\n- Access to your orders/invoices database (already configured)\n\nOnce LLM is enabled, I'll analyze today's revenue, compare to 7-day average, identify trends, and flag anomalies. For now, please check the Analytics dashboard for live numbers.`;
    } else if (lower.includes("approv") || lower.includes("decision")) {
      response = `**${agentName} Agent — Decision Stub Response**\n\nAny action requiring your approval will appear in the Approval Queue panel. I cannot execute sensitive actions (financial transfers, record deletions, config changes) without your explicit approval. In stub mode, I will:\n\n1. Flag decisions that exceed my spending limits\n2. Create approval requests with full reasoning\n3. Wait for your decision before proceeding\n\nEnable LLM via GEMINI_API_KEY for richer decision reasoning.`;
    } else if (lower.includes("hello") || lower.includes("hi ") || lower === "hi" || lower.includes("salam")) {
      response = `Hello! I'm the ${agentName} Agent, currently in stub mode. I'm ready to handle tasks, participate in workflows, and communicate with other agents. Ask me about company status, financials, or anything else — or set GEMINI_API_KEY to unlock my full reasoning capabilities.`;
    } else {
      response = `**${agentName} Agent — Stub Response**\n\nI received your query: "${userContent.slice(0, 200)}${userContent.length > 200 ? "..." : ""}"\n\nIn stub mode (no LLM key configured), I can't generate intelligent natural-language responses, but I have:\n- Created a task in my queue to track this\n- Logged the interaction to the audit trail\n- Notified the relevant agents via the message bus\n\nTo enable real AI reasoning, set GEMINI_API_KEY in your Vercel environment variables. Until then, all my operational capabilities (task tracking, workflow execution, memory retrieval, approval routing) work normally.`;
    }

    return {
      content: response,
      powered: false,
      latencyMs: Date.now() - start,
      provider: "stub",
    };
  }
}

// ────────────────────────────────────────────────────────────────────────────
// Gemini LLM — uses @google/generative-ai
// ────────────────────────────────────────────────────────────────────────────

class GeminiLLM implements LLMProvider {
  name = "gemini";
  isAvailable: boolean;
  private apiKey: string;
  private model: string;

  constructor() {
    // Support both GEMINI_API_KEY (preferred) and GOOGLE_API_KEY (alias)
    this.apiKey = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY || "";
    // Default model: gemini-2.0-flash (stable, fast, supports JSON mode).
    // Override with GEMINI_MODEL env var if you want a different model
    // (e.g. gemini-1.5-flash, gemini-2.5-flash, gemini-2.0-flash-exp).
    this.model = process.env.GEMINI_MODEL || "gemini-2.0-flash";
    this.isAvailable = !!this.apiKey;
  }

  async generate(req: LLMRequest): Promise<LLMResponse> {
    const start = Date.now();
    if (!this.isAvailable) {
      throw new Error("GEMINI_API_KEY not configured");
    }

    // ── 429 Retry with exponential backoff ──────────────────────────────────
    // Gemini's free tier has aggressive rate limits (e.g. 15 RPM, 1500/day).
    // When we hit a 429, Google's response includes a "retryDelay" hint
    // (e.g. "49s"). We honor that hint when present, otherwise we use
    // exponential backoff: 2s, 4s, 8s. Max 3 retries.
    const MAX_RETRIES = 3;
    const BASE_BACKOFF_MS = 2_000;

    for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
      try {
        // Dynamic import so the SDK is only loaded when actually needed
        const GoogleGenAI = await import("@google/generative-ai").catch(() => null);
        if (!GoogleGenAI || !GoogleGenAI.GoogleGenerativeAI) {
          throw new Error("@google/generative-ai not installed");
        }

        const genAI = new GoogleGenAI.GoogleGenerativeAI(this.apiKey);
        const model = genAI.getGenerativeModel({
          model: this.model,
          generationConfig: {
            temperature: req.temperature ?? 0.4,
            maxOutputTokens: req.maxTokens ?? 800,
            ...(req.responseFormat === "json"
              ? { responseMimeType: "application/json" as const }
              : {}),
          },
        });

        // Convert LLMMessage[] → Gemini format
        const systemMsgs = req.messages.filter((m) => m.role === "system");
        const conversationMsgs = req.messages.filter((m) => m.role !== "system");
        const systemInstruction = systemMsgs.map((m) => m.content).join("\n\n") || undefined;
        const contents = conversationMsgs.map((m) => ({
          role: m.role === "assistant" ? "model" : "user",
          parts: [{ text: m.content }],
        }));

        const result = await (model as any).generateContent({
          contents,
          ...(systemInstruction ? { systemInstruction } : {}),
        });

        const content =
          result?.response?.text?.() ||
          result?.response?.candidates?.[0]?.content?.parts?.map((p: any) => p.text).join("") ||
          "I couldn't generate a response. Please try again.";

        const tokensUsed =
          result?.response?.usageMetadata?.totalTokenCount ?? undefined;

        return {
          content,
          powered: true,
          tokensUsed,
          latencyMs: Date.now() - start,
          provider: `gemini (${this.model})`,
        };
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);

        // ── Detect 429 (quota exceeded) ─────────────────────────────────────
        // Gemini's 429 response looks like:
        //   [GoogleGenerativeAI Error]: Error fetching from ... [429 Too Many Requests]
        //   You exceeded your current quota ... Please retry in 49.462559532s.
        const is429 = /429|too many requests|quota|rate.?limit/i.test(msg);

        if (is429 && attempt < MAX_RETRIES) {
          // Parse Google's retryDelay hint (e.g. "Please retry in 49s" or
          // "retryDelay":"49s"). Default to exponential backoff if not found.
          let delayMs = BASE_BACKOFF_MS * Math.pow(2, attempt);
          const delayMatch = msg.match(/retry[^0-9]*?(\d+(?:\.\d+)?)\s*s/i);
          if (delayMatch) {
            const parsedSeconds = parseFloat(delayMatch[1]);
            if (!isNaN(parsedSeconds) && parsedSeconds > 0 && parsedSeconds < 120) {
              delayMs = Math.min(parsedSeconds * 1000, 60_000);
            }
          }
          logger.warn(`[GeminiLLM] 429 quota hit — retry ${attempt + 1}/${MAX_RETRIES} in ${Math.round(delayMs / 1000)}s`);
          await new Promise((r) => setTimeout(r, delayMs));
          continue; // Retry
        }

        // ── Terminal error — give a friendly, actionable message ────────────
        logger.error("[GeminiLLM] Generation failed, falling back to stub", { error: msg, model: this.model });

        // Translate raw Google API errors into user-friendly hints
        let friendlyError = msg;
        if (is429) {
          friendlyError =
            "Gemini API quota exceeded. Your free-tier daily/minute limit is reached. " +
            "Options: (1) wait ~1 minute and try again, (2) upgrade your Google AI Studio " +
            "plan to a paid tier at https://aistudio.google.com/pricing, or (3) set a " +
            "different LLM provider (ZAI_API_KEY).";
        } else if (/api key not valid|invalid_api_key/i.test(msg)) {
          friendlyError =
            "GEMINI_API_KEY is invalid. Generate a new key at " +
            "https://aistudio.google.com/app/apikey and update Vercel env vars.";
        } else if (/model.*not found|not supported/i.test(msg)) {
          friendlyError =
            `Model "${this.model}" not found. Set GEMINI_MODEL env var to a valid name ` +
            "(e.g. gemini-2.0-flash, gemini-1.5-flash, gemini-2.5-flash).";
        } else if (/permission|forbidden|403/i.test(msg)) {
          friendlyError =
            "Gemini API returned 403 Forbidden. Your API key may not have access to " +
            "the requested model, or your Google Cloud project may not have the " +
            "Generative Language API enabled.";
        }

        // Fall back to stub — never crash the agent. But include the friendly
        // error in the response so the user can see WHY Gemini failed.
        const stub = new StubLLM();
        const res = await stub.generate(req);
        const errorHint = `[Gemini Error: ${friendlyError.slice(0, 300)}] \n\n`;
        return {
          ...res,
          content: errorHint + res.content,
          provider: `stub (gemini-failed: ${friendlyError.slice(0, 80)})`,
          lastError: friendlyError,
        };
      }
    }

    // Should never reach here — loop either returns or throws+catches
    const stub = new StubLLM();
    const res = await stub.generate(req);
    return {
      ...res,
      provider: `stub (gemini-unreachable)`,
      lastError: "Gemini retries exhausted without throwing",
    };
  }
}

// ────────────────────────────────────────────────────────────────────────────
// Z.ai LLM — uses z-ai-web-dev-sdk
// ────────────────────────────────────────────────────────────────────────────

class ZaiLLM implements LLMProvider {
  name = "zai";
  isAvailable: boolean;

  constructor() {
    this.isAvailable = !!process.env.ZAI_API_KEY;
  }

  async generate(req: LLMRequest): Promise<LLMResponse> {
    const start = Date.now();
    if (!this.isAvailable) {
      throw new Error("ZAI_API_KEY not configured");
    }

    try {
      // Dynamic import so the SDK is only loaded when actually needed
      // (keeps the bundle small for orgs that don't use LLM features).
      const ZAI = await import("z-ai-web-dev-sdk").catch(() => null);
      if (!ZAI || !ZAI.default) {
        throw new Error("z-ai-web-dev-sdk not installed");
      }

      const zai = await ZAI.default.create();
      const completion = await zai.chat.completions.create({
        messages: req.messages,
        temperature: req.temperature ?? 0.4,
        max_tokens: req.maxTokens ?? 800,
      });

      const content =
        completion.choices?.[0]?.message?.content ||
        "I couldn't generate a response. Please try again.";

      return {
        content,
        powered: true,
        tokensUsed: completion.usage?.total_tokens,
        latencyMs: Date.now() - start,
        provider: "zai",
      };
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error("[ZaiLLM] Generation failed, falling back to stub", { error: msg });
      // Fall back to stub — never crash the agent
      const stub = new StubLLM();
      const res = await stub.generate(req);
      return { ...res, provider: `stub (zai-failed: ${msg.slice(0, 80)})` };
    }
  }
}

// ────────────────────────────────────────────────────────────────────────────
// Provider Selection
// ────────────────────────────────────────────────────────────────────────────

let _provider: LLMProvider | null = null;

export function getLLMProvider(): LLMProvider {
  if (_provider) return _provider;

  // Priority: Gemini > Z.ai > Stub
  if (process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY) {
    _provider = new GeminiLLM();
    if (_provider.isAvailable) {
      logger.info("[AI Team] Using Gemini LLM provider");
      return _provider;
    }
  }

  if (process.env.ZAI_API_KEY) {
    _provider = new ZaiLLM();
    if (_provider.isAvailable) {
      logger.info("[AI Team] Using Z.ai LLM provider");
      return _provider;
    }
  }

  _provider = new StubLLM();
  logger.warn("[AI Team] Using stub LLM provider — set GEMINI_API_KEY or ZAI_API_KEY for real AI responses");
  return _provider;
}

export function isLLMPowered(): boolean {
  return getLLMProvider().name !== "stub" && getLLMProvider().isAvailable;
}

// Returns a human-readable label for the dashboard UI
export function getLLMProviderLabel(): string {
  return getLLMProvider().name;
}

// ─────────────────────────────────────────────────────────────────────────────
// Health Check — tests if the LLM provider ACTUALLY works (not just if the
// env var is set). Returns detailed diagnostics so the Owner can see exactly
// why Gemini/Z.ai is failing. Used by /api/ai-team/health.
// ─────────────────────────────────────────────────────────────────────────────

export interface LLMHealthCheck {
  configured: boolean;        // env var is set
  providerName: string;       // "gemini" | "zai" | "stub"
  model?: string;             // which model is being used
  apiKeyPresent: boolean;     // is the key non-empty?
  apiKeyPrefix?: string;      // first 4 chars (safe to log, helps diagnose format issues)
  actualCallSucceeded: boolean; // did a real generate() call return powered=true?
  errorMessage?: string;      // if failed, the error
  latencyMs?: number;         // how long the test call took
  responseSample?: string;    // first 200 chars of the test response
}

export async function checkLLMHealth(): Promise<LLMHealthCheck> {
  const provider = getLLMProvider();
  const hasGeminiKey = !!(process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY);
  const hasZaiKey = !!process.env.ZAI_API_KEY;
  const apiKey = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY || process.env.ZAI_API_KEY || "";

  const base: LLMHealthCheck = {
    configured: provider.name !== "stub",
    providerName: provider.name,
    model: provider.name === "gemini" ? (process.env.GEMINI_MODEL || "gemini-2.0-flash") : undefined,
    apiKeyPresent: !!apiKey,
    apiKeyPrefix: apiKey ? apiKey.slice(0, 4) + "..." : undefined,
    actualCallSucceeded: false,
  };

  if (provider.name === "stub") {
    return {
      ...base,
      errorMessage: hasGeminiKey
        ? "GEMINI_API_KEY is set but provider resolved to stub — check server logs"
        : hasZaiKey
        ? "ZAI_API_KEY is set but provider resolved to stub — check server logs"
        : "No LLM API key configured. Set GEMINI_API_KEY or ZAI_API_KEY in Vercel env vars.",
    };
  }

  // Run an actual test call
  try {
    const start = Date.now();
    const res = await provider.generate({
      messages: [
        { role: "system", content: "You are a test bot. Reply with exactly: OK" },
        { role: "user", content: "Reply with exactly one word: OK" },
      ],
      temperature: 0,
      maxTokens: 10,
    });

    return {
      ...base,
      actualCallSucceeded: res.powered,
      latencyMs: Date.now() - start,
      responseSample: res.content.slice(0, 200),
      errorMessage: res.powered ? undefined : res.lastError || "LLM returned powered=false (fell back to stub)",
    };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    return {
      ...base,
      errorMessage: `Health check threw: ${msg}`,
    };
  }
}
