// ============================================================================
// AI Workforce Module — Pluggable LLM Interface
// ============================================================================
// The AI Workforce can run with two LLM backends:
//
//   1. StubLLM  — rule-based responses, requires NO API key. Used for testing
//                 and for orgs that haven't configured an LLM provider yet.
//                 Every agent returns a deterministic, contextual response.
//
//   2. ZaiLLM   — uses z-ai-web-dev-sdk (the same SDK used by other Valtriox
//                 AI features). Activated when ZAI_API_KEY is set in env.
//                 Falls back to StubLLM on any error.
//
// To add a new provider (OpenAI, Anthropic, etc.), implement the LLMProvider
// interface and add a branch in getLLMProvider().
// ============================================================================

import logger from "@/lib/logger";

export interface LLMMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

export interface LLMRequest {
  messages: LLMMessage[];
  // Lower temperature = more deterministic. Agents should use 0.3-0.5.
  temperature?: number;
  // Max tokens for the response
  maxTokens?: number;
  // Optional: response format hint (e.g., "json" for structured output)
  responseFormat?: "text" | "json";
}

export interface LLMResponse {
  content: string;
  // Whether the response was generated by a real LLM or fell back to stub
  powered: boolean;
  // Tokens used (only set by real LLM)
  tokensUsed?: number;
  // Latency in ms
  latencyMs: number;
}

export interface LLMProvider {
  name: string;
  isAvailable: boolean;
  generate(req: LLMRequest): Promise<LLMResponse>;
}

// ────────────────────────────────────────────────────────────────────────────
// Stub LLM — rule-based, deterministic, no API key required
// ────────────────────────────────────────────────────────────────────────────

class StubLLM implements LLMProvider {
  name = "stub";
  isAvailable = true;

  async generate(req: LLMRequest): Promise<LLMResponse> {
    const start = Date.now();
    const lastUser = [...req.messages].reverse().find((m) => m.role === "user");
    const userContent = lastUser?.content || "";
    const systemMsg = req.messages.find((m) => m.role === "system")?.content || "";

    // Extract agent name from system prompt
    const agentNameMatch = systemMsg.match(/You are the (.*?) agent/i);
    const agentName = agentNameMatch ? agentNameMatch[1] : "AI";

    // Detect intent from the query
    const lower = userContent.toLowerCase();
    let response: string;

    if (lower.includes("summary") || lower.includes("brief") || lower.includes("status")) {
      response = `**${agentName} Agent — Stub Mode Report**\n\nI'm operating in stub mode (no LLM API key configured). Here's what I'd normally do:\n\n1. Retrieve relevant memory entries from the knowledge store\n2. Query the live business database for current metrics\n3. Synthesize a ${agentName.toLowerCase()}-focused summary\n4. Recommend 2-3 actions for your review\n\nTo enable real AI responses, set the \`ZAI_API_KEY\` environment variable in your Vercel project settings. Once set, I'll provide intelligent, context-aware responses.\n\nIn the meantime, all my workflows, tasks, and message-bus communications are fully functional — only the natural-language reasoning is stubbed.`;
    } else if (lower.includes("revenue") || lower.includes("finance") || lower.includes("money")) {
      response = `**${agentName} Agent — Financial Stub Response**\n\nTo provide real revenue insights, I need:\n- A connected LLM provider (set \`ZAI_API_KEY\`)\n- Access to your orders/invoices database (already configured)\n\nOnce LLM is enabled, I'll analyze today's revenue, compare to 7-day average, identify trends, and flag anomalies. For now, please check the Analytics dashboard for live numbers.`;
    } else if (lower.includes("approv") || lower.includes("decision")) {
      response = `**${agentName} Agent — Decision Stub Response**\n\nAny action requiring your approval will appear in the Approval Queue panel. I cannot execute sensitive actions (financial transfers, record deletions, config changes) without your explicit approval. In stub mode, I will:\n\n1. Flag decisions that exceed my spending limits\n2. Create approval requests with full reasoning\n3. Wait for your decision before proceeding\n\nEnable LLM via \`ZAI_API_KEY\` for richer decision reasoning.`;
    } else if (lower.includes("hello") || lower.includes("hi ") || lower === "hi" || lower.includes("salam")) {
      response = `Hello! I'm the ${agentName} Agent, currently in stub mode. I'm ready to handle tasks, participate in workflows, and communicate with other agents. Ask me about company status, financials, or anything else — or set \`ZAI_API_KEY\` to unlock my full reasoning capabilities.`;
    } else {
      response = `**${agentName} Agent — Stub Response**\n\nI received your query: "${userContent.slice(0, 200)}${userContent.length > 200 ? "..." : ""}"\n\nIn stub mode (no LLM key configured), I can't generate intelligent natural-language responses, but I have:\n- Created a task in my queue to track this\n- Logged the interaction to the audit trail\n- Notified the relevant agents via the message bus\n\nTo enable real AI reasoning, set \`ZAI_API_KEY\` in your Vercel environment variables. Until then, all my operational capabilities (task tracking, workflow execution, memory retrieval, approval routing) work normally.`;
    }

    return {
      content: response,
      powered: false,
      latencyMs: Date.now() - start,
    };
  }
}

// ────────────────────────────────────────────────────────────────────────────
// Z.ai LLM — uses z-ai-web-dev-sdk
// ────────────────────────────────────────────────────────────────────────────

class ZaiLLM implements LLMProvider {
  name = "zai";
  isAvailable: boolean;

  constructor() {
    this.isAvailable = !!process.env.ZAI_API_KEY;
  }

  async generate(req: LLMRequest): Promise<LLMResponse> {
    const start = Date.now();
    if (!this.isAvailable) {
      throw new Error("ZAI_API_KEY not configured");
    }

    try {
      // Dynamic import so the SDK is only loaded when actually needed
      // (keeps the bundle small for orgs that don't use LLM features).
      const ZAI = await import("z-ai-web-dev-sdk").catch(() => null);
      if (!ZAI || !ZAI.default) {
        throw new Error("z-ai-web-dev-sdk not installed");
      }

      const zai = await ZAI.default.create();
      const completion = await zai.chat.completions.create({
        messages: req.messages,
        temperature: req.temperature ?? 0.4,
        max_tokens: req.maxTokens ?? 800,
      });

      const content =
        completion.choices?.[0]?.message?.content ||
        "I couldn't generate a response. Please try again.";

      return {
        content,
        powered: true,
        tokensUsed: completion.usage?.total_tokens,
        latencyMs: Date.now() - start,
      };
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error("[ZaiLLM] Generation failed, falling back to stub", { error: msg });
      // Fall back to stub — never crash the agent
      const stub = new StubLLM();
      return stub.generate(req);
    }
  }
}

// ────────────────────────────────────────────────────────────────────────────
// Provider Selection
// ────────────────────────────────────────────────────────────────────────────

let _provider: LLMProvider | null = null;

export function getLLMProvider(): LLMProvider {
  if (_provider) return _provider;

  // Priority: ZAI > Stub
  if (process.env.ZAI_API_KEY) {
    _provider = new ZaiLLM();
    if (_provider.isAvailable) {
      logger.info("[AI Team] Using Z.ai LLM provider");
      return _provider;
    }
  }

  _provider = new StubLLM();
  logger.warn("[AI Team] Using stub LLM provider — set ZAI_API_KEY for real AI responses");
  return _provider;
}

export function isLLMPowered(): boolean {
  return getLLMProvider().name !== "stub" && getLLMProvider().isAvailable;
}
