#!/usr/bin/env node
// ============================================================================
// Real psql integration test — Round 13 R13-2
// ============================================================================
// Purpose:
//   Expert feedback: "Mock tests real psql output represent nahi karte.
//   BEGIN/COMMIT ke saath actual psql output aur error behaviour ko
//   disposable, non-production database par validate karein."
//
// Approach:
//   - Uses a disposable PostgreSQL instance (postgres:16 in CI).
//   - Sets up a dedicated NON-superuser role (superuser bypasses
//     BEGIN READ ONLY enforcement — production uses non-superuser).
//   - Runs real psql invocations with BEGIN READ ONLY; ...; COMMIT;
//     wrappers exactly as the harness does.
//   - Validates actual stdout/stderr/exit-code behavior.
//
// Local dev behavior:
//   - If TEST_DATABASE_URL is not set, the test SKIPS (exit 0).
//   - No local PostgreSQL required.
// ============================================================================

import { spawnSync } from "node:child_process";
import {
  assertDisposableTarget,
  buildDbNameVerificationDoBlock,
  buildClusterVerificationDoBlock,
} from "./disposable-target-guard.mjs";
import {
  buildCleanupGuard,
  buildCleanupSequence,
} from "../cleanup-runner.mjs";

const TEST_DATABASE_URL = process.env.TEST_DATABASE_URL;

if (!TEST_DATABASE_URL) {
  console.log("\nSKIP: TEST_DATABASE_URL not set (local dev / no DB).\n");
  process.exit(0);
}

// Round 15 R15-1: refuse destructive DDL against non-disposable targets.
// Must be called BEFORE any DROP/CREATE statement. Fail-closed.
// Round 17 R17-1: disposable-target identity is proven by a per-run marker
// injected by the CI workflow. Network-address classification is removed.
const EXPECTED_DB_NAME = process.env.DISPOSABLE_DB_NAME;
assertDisposableTarget(TEST_DATABASE_URL, { expectedDbName: EXPECTED_DB_NAME });

// R19-1: cluster identity binding — independently trusted anchor for
// the mutation target. system_identifier is captured by the CI workflow
// before the test runs, is immutable per cluster, and is verified in the
// SAME transaction as the DDL (setup and cleanup).
const TRUSTED_CLUSTER_ID = process.env.TRUSTED_CLUSTER_ID;
if (!TRUSTED_CLUSTER_ID) {
  console.error("TRUSTED_CLUSTER_ID: not set. Refusing to proceed.");
  process.exit(1);
}

// ── Setup: derive superuser + readonly role URLs ────────────────────────
const superUrl = new URL(TEST_DATABASE_URL);

// R19-2: per-run role name. PostgreSQL roles are cluster-wide, so a
// fixed name would be shared across runs, attempts, and clusters —
// unsafe for cleanup (DROP ROLE) and untraceable to this run. The name
// is generated by the CI workflow before the test runs and is validated
// here against the expected pattern (defence in depth).
const ROLE_NAME = process.env.TEST_ROLE_NAME;
if (!ROLE_NAME) {
  console.error("TEST_ROLE_NAME: not set. Refusing to proceed.");
  process.exit(1);
}
if (!/^audit_ro_[0-9]+_[0-9]+_[a-f0-9]+$/.test(ROLE_NAME)) {
  console.error("TEST_ROLE_NAME: unexpected format: " + ROLE_NAME);
  process.exit(1);
}
const ROLE_PASSWORD = ROLE_NAME + "_pass";

const roUrl = new URL(TEST_DATABASE_URL);
roUrl.username = ROLE_NAME;
roUrl.password = ROLE_PASSWORD;

const TEST_TABLE = "test_r13_readonly_enforcement";

// ── psql runner (mirrors harness: -t -A -F \t + optional BEGIN READ ONLY) ──
// R16-1: Fail-closed env isolation (mirrors notification-inventory.mjs R14-1).
// Ambient PG* vars are NEVER inherited — only an explicit operational allowlist
// plus the URL-derived PG* values. Prevents PGHOSTADDR/PGSERVICE/PGOPTIONS/etc.
// from overriding the URL target after assertDisposableTarget() has passed.
const SAFE_PASSTHROUGH = [
  "PATH", "Path", "HOME", "LANG", "LC_ALL", "LC_MESSAGES",
  "TZ", "TERM", "USER", "LOGNAME", "SHELL",
];

function makePsqlEnv(urlObj) {
  const env = {};
  for (const key of SAFE_PASSTHROUGH) {
    if (process.env[key] !== undefined) {
      env[key] = process.env[key];
    }
  }
  env.PGPASSWORD = decodeURIComponent(urlObj.password);
  env.PGUSER = decodeURIComponent(urlObj.username);
  env.PGHOST = urlObj.hostname;
  env.PGPORT = urlObj.port || "5432";
  env.PGDATABASE = urlObj.pathname.replace(/^\//, "");
  env.PGSSLMODE = "prefer";
  return env;
}

const superEnv = makePsqlEnv(superUrl);
const roEnv = makePsqlEnv(roUrl);

function psql(sql, { guard = true, env = superEnv } = {}) {
  // Semicolon after ${sql} required — see R13-2b.
  const guardedSql = guard ? `BEGIN READ ONLY;\n${sql};\nCOMMIT;` : sql;
  const result = spawnSync(
    "psql",
    ["-t", "-A", "-F", "\t", "-c", guardedSql],
    { env, encoding: "utf8", maxBuffer: 10 * 1024 * 1024, timeout: 30_000 }
  );
  // R13-2c: mirror harness — strip BEGIN/COMMIT command tags.
  if (guard && typeof result.stdout === "string") {
    result.stdout = result.stdout
      .split("\n")
      .filter((line) => line !== "BEGIN" && line !== "COMMIT")
      .join("\n");
  }
  return result;
}

// ── Test harness ────────────────────────────────────────────────────────
let passed = 0;
let failed = 0;

// R20-5a: redact secrets before logging error messages.
// CodeQL js/clear-text-logging (alert #53): psql stderr may echo the
// connection URL with password. Sanitize at every log sink.
function redactSecrets(s) {
  return String(s)
    .replace(/postgres(?:ql)?:\/\/[^:\s/]+:[^@\s/]+@/gi, "postgresql://[REDACTED]@")
    .replace(/password=[^\s&'\"]+/gi, "password=[REDACTED]");
}

function test(name, fn) {
  try {
    fn();
    console.log(`  ✓ ${name}`);
    passed++;
  } catch (err) {
    console.error(`  ✗ ${name}`);
    console.error(`    ${redactSecrets(err.message)}`);
    failed++;
  }
}

function assertEq(actual, expected, label) {
  if (actual !== expected) {
    throw new Error(
      `${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`
    );
  }
}

function assertTrue(cond, label) {
  if (!cond) throw new Error(`${label}: expected true`);
}

function assertContains(haystack, needle, label) {
  if (!haystack.includes(needle)) {
    throw new Error(
      `${label}: expected to contain ${JSON.stringify(needle)}, got: ${haystack.slice(0, 400)}`
    );
  }
}

console.log("\nReal psql integration tests (Round 13 R13-2):\n");
// ── R17-3: Negative pre-tests — run BEFORE any real DDL ────────
// Expert Round 16 concern (P0 #3): "Negative test setup DDL se pehle
// hostile/non-disposable target introduce kare aur prove kare ke zero
// destructive statements chalin aur known target state unchanged rahi."

// R20-3: comprehensive snapshot of the target database state (V3).
// Captures all 27 non-system categories that destructive DDL could touch.
//
// V1 (5):     tables, columns, roles, table_grants, column_grants
// R19-4 (14): row_counts, row_counts_approx, database_grants,
//             schema_grants, role_attributes, memberships, ownership,
//             defaults, constraints, indexes, triggers, rls, sequences,
//             views
// R20-3a:     determinism fix - ORDER BY 1 inside string_agg refers to
//             the aggregate's argument position, not outer-query columns.
//             Replaced with explicit column references on ALL categories.
// R20-3c:     db_role_setting - actual storage for ALTER ROLE ... SET
//             (S12). pg_roles.rolconfig does NOT reflect per-database
//             role settings.
// R20-3d:     rls_flags - relrowsecurity / relforcerowsecurity. The
//             pg_policies category captures policy definitions only.
// R20-3e:     matviews, function_grants, type_grants, sequence_grants,
//             default_acl, shared_dependencies; ownership expanded to
//             cover rel/schema/func/type/db owners.
//
// Result: deterministic, ordered string. Any query failure aborts
// capture (fail-closed, no silent skip).
function captureTargetState(env) {
  const queries = [
    // ── V1 categories ───────────────────────────────────────────
    ["tables",
     "SELECT COALESCE(string_agg(schemaname||'.'||tablename, '|' " +
     "  ORDER BY schemaname, tablename), '') " +
     "FROM pg_tables WHERE schemaname NOT IN ('pg_catalog','information_schema')"],
    ["columns",
     "SELECT COALESCE(string_agg(" +
     "  table_schema||'.'||table_name||'.'||column_name||':'||data_type, '|' " +
     "  ORDER BY table_schema, table_name, column_name), '') " +
     "FROM information_schema.columns " +
     "WHERE table_schema NOT IN ('pg_catalog','information_schema')"],
    ["roles",
     "SELECT COALESCE(string_agg(rolname, '|' ORDER BY rolname), '') " +
     "FROM pg_roles WHERE rolname NOT LIKE 'pg_%'"],
    ["table_grants",
     "SELECT COALESCE(string_agg(" +
     "  table_schema||'.'||table_name||':'||grantee||':'||privilege_type, '|' " +
     "  ORDER BY table_schema, table_name, grantee, privilege_type), '') " +
     "FROM information_schema.role_table_grants " +
     "WHERE table_schema NOT IN ('pg_catalog','information_schema')"],
    ["column_grants",
     "SELECT COALESCE(string_agg(" +
     "  table_schema||'.'||table_name||'.'||column_name||':'||grantee||':'||privilege_type, '|' " +
     "  ORDER BY table_schema, table_name, column_name, grantee, privilege_type), '') " +
     "FROM information_schema.column_privileges " +
     "WHERE table_schema NOT IN ('pg_catalog','information_schema')"],
    // ── R19-4 categories ────────────────────────────────────────
    ["row_counts",
     "SELECT COALESCE(string_agg(" +
     "  schemaname||'.'||tablename||'='||" +
     "  COALESCE((xpath('/row/c/text()', query_to_xml(" +
     "    format('SELECT count(*) AS c FROM %I.%I', schemaname, tablename)," +
     "    false, true, '')))[1]::text, '?'), '|' " +
     "  ORDER BY schemaname, tablename), '') " +
     "FROM pg_tables WHERE schemaname NOT IN ('pg_catalog','information_schema')"],
    ["row_counts_approx",
     "SELECT COALESCE(string_agg(" +
     "  n.nspname||'.'||c.relname||'='||c.reltuples::bigint::text, '|' " +
     "  ORDER BY n.nspname, c.relname), '') " +
     "FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace " +
     "WHERE c.relkind = 'r' " +
     "  AND n.nspname NOT IN ('pg_catalog','information_schema')"],
    ["database_grants",
     "SELECT COALESCE(string_agg(" +
     "  datname||'|'||grantee||'|'||privilege_type, '||' " +
     "  ORDER BY datname, grantee, privilege_type), '') " +
     "FROM (SELECT d.datname, COALESCE(r.rolname, 'PUBLIC') AS grantee, " +
     "             a.privilege_type " +
     "      FROM pg_database d " +
     "      CROSS JOIN LATERAL aclexplode(COALESCE(d.datacl, acldefault('d', d.datdba))) a " +
     "      LEFT JOIN pg_roles r ON r.oid = a.grantee " +
     "      WHERE d.datname NOT LIKE 'template%') sub"],
    ["schema_grants",
     "SELECT COALESCE(string_agg(" +
     "  nspname||'|'||COALESCE(rolname, 'PUBLIC')||'|'||privilege_type, '||' " +
     "  ORDER BY nspname, rolname, privilege_type), '') " +
     "FROM (SELECT n.nspname, r.rolname, a.privilege_type " +
     "      FROM pg_namespace n " +
     "      CROSS JOIN LATERAL aclexplode(COALESCE(n.nspacl, acldefault('n', n.nspowner))) a " +
     "      LEFT JOIN pg_roles r ON r.oid = a.grantee " +
     "      WHERE n.nspname NOT IN ('pg_catalog','information_schema','pg_toast')) sub"],
    ["role_attributes",
     "SELECT COALESCE(string_agg(" +
     "  rolname||'|super='||rolsuper||'|createdb='||rolcreatedb||'|createrole='||rolcreaterole" +
     "  ||'|inherit='||rolinherit||'|login='||rolcanlogin||'|replication='||rolreplication" +
     "  ||'|bypassrls='||rolbypassrls||'|connlimit='||rolconnlimit" +
     "  ||'|validuntil='||COALESCE(rolvaliduntil::text,'null')" +
     "  , '||' ORDER BY rolname), '') " +
     "FROM pg_roles WHERE rolname NOT LIKE 'pg_%'"],
    ["memberships",
     "SELECT COALESCE(string_agg(" +
     "  m.roleid::regrole::text||'<-'||m.member::regrole::text||'|admin='||m.admin_option" +
     "  , '||' ORDER BY m.roleid, m.member), '') " +
     "FROM pg_auth_members m"],
    ["ownership",
     // R20-3e: expanded to rel + schema + function + type + database
     // owners (was rel only in R19-4).
     "SELECT COALESCE(string_agg(entry, '||' ORDER BY entry), '') FROM (" +
     "  SELECT 'rel:'||n.nspname||'.'||c.relname||'='||pg_get_userbyid(c.relowner) AS entry " +
     "    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace " +
     "    WHERE n.nspname NOT IN ('pg_catalog','information_schema','pg_toast') " +
     "      AND c.relkind IN ('r','v','m','S','f','p') " +
     "  UNION ALL " +
     "  SELECT 'schema:'||n.nspname||'='||pg_get_userbyid(n.nspowner) " +
     "    FROM pg_namespace n " +
     "    WHERE n.nspname NOT IN ('pg_catalog','information_schema','pg_toast') " +
     "  UNION ALL " +
     "  SELECT 'func:'||n.nspname||'.'||p.proname||'('||pg_get_function_identity_arguments(p.oid)||')='" +
     "         ||pg_get_userbyid(p.proowner) " +
     "    FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace " +
     "    WHERE n.nspname NOT IN ('pg_catalog','information_schema','pg_toast') " +
     "  UNION ALL " +
     "  SELECT 'type:'||n.nspname||'.'||t.typname||'='||pg_get_userbyid(t.typowner) " +
     "    FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace " +
     "    WHERE n.nspname NOT IN ('pg_catalog','information_schema','pg_toast') " +
     "  UNION ALL " +
     "  SELECT 'db:'||d.datname||'='||pg_get_userbyid(d.datdba) " +
     "    FROM pg_database d WHERE d.datname NOT LIKE 'template%' " +
     ") own"],
    ["defaults",
     "SELECT COALESCE(string_agg(" +
     "  n.nspname||'.'||c.relname||'.'||a.attname||'='||pg_get_expr(ad.adbin, ad.adrelid)" +
     "  , '||' ORDER BY n.nspname, c.relname, a.attname), '') " +
     "FROM pg_attrdef ad " +
     "JOIN pg_class c ON c.oid = ad.adrelid " +
     "JOIN pg_namespace n ON n.oid = c.relnamespace " +
     "JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = ad.adnum " +
     "WHERE n.nspname NOT IN ('pg_catalog','information_schema','pg_toast')"],
    ["constraints",
     "SELECT COALESCE(string_agg(" +
     "  n.nspname||'.'||c.relname||'|'||con.conname||'|'||con.contype::text||'|'||pg_get_constraintdef(con.oid)" +
     "  , '||' ORDER BY n.nspname, c.relname, con.conname), '') " +
     "FROM pg_constraint con " +
     "JOIN pg_class c ON c.oid = con.conrelid " +
     "JOIN pg_namespace n ON n.oid = c.relnamespace " +
     "WHERE n.nspname NOT IN ('pg_catalog','information_schema','pg_toast')"],
    ["indexes",
     "SELECT COALESCE(string_agg(" +
     "  schemaname||'.'||tablename||'|'||indexname||'|'||indexdef" +
     "  , '||' ORDER BY schemaname, tablename, indexname), '') " +
     "FROM pg_indexes " +
     "WHERE schemaname NOT IN ('pg_catalog','information_schema','pg_toast')"],
    ["triggers",
     "SELECT COALESCE(string_agg(" +
     "  n.nspname||'.'||c.relname||'|'||t.tgname||'|'||pg_get_triggerdef(t.oid)" +
     "  , '||' ORDER BY n.nspname, c.relname, t.tgname), '') " +
     "FROM pg_trigger t " +
     "JOIN pg_class c ON c.oid = t.tgrelid " +
     "JOIN pg_namespace n ON n.oid = c.relnamespace " +
     "WHERE NOT t.tgisinternal " +
     "  AND n.nspname NOT IN ('pg_catalog','information_schema','pg_toast')"],
    ["rls",
     "SELECT COALESCE(string_agg(" +
     "  schemaname||'.'||tablename||'|'||policyname||'|'||cmd" +
     "  ||'|'||COALESCE(qual,'')||'|'||COALESCE(with_check,'')" +
     "  , '||' ORDER BY schemaname, tablename, policyname), '') " +
     "FROM pg_policies " +
     "WHERE schemaname NOT IN ('pg_catalog','information_schema','pg_toast')"],
    ["sequences",
     "SELECT COALESCE(string_agg(" +
     "  schemaname||'.'||sequencename||'|start='||start_value" +
     "  ||'|min='||min_value||'|max='||max_value" +
     "  ||'|inc='||increment_by||'|cycle='||cycle||'|cache='||cache_size" +
     "  , '||' ORDER BY schemaname, sequencename), '') " +
     "FROM pg_sequences " +
     "WHERE schemaname NOT IN ('pg_catalog','information_schema','pg_toast')"],
    ["views",
     "SELECT COALESCE(string_agg(" +
     "  schemaname||'.'||viewname||'|'||definition" +
     "  , '||' ORDER BY schemaname, viewname), '') " +
     "FROM pg_views " +
     "WHERE schemaname NOT IN ('pg_catalog','information_schema','pg_toast')"],
    // ── R20-3 new categories ────────────────────────────────────
    ["db_role_setting",
     "SELECT COALESCE(string_agg(" +
     "  s.setrole::regrole::text||'|'||" +
     "  COALESCE(d.datname, 'ALL')||'|'||" +
     "  array_to_string(s.setconfig, ','), '||' " +
     "  ORDER BY s.setrole::regrole::text, s.setdatabase), '') " +
     "FROM pg_db_role_setting s " +
     "LEFT JOIN pg_database d ON d.oid = s.setdatabase"],
    ["rls_flags",
     "SELECT COALESCE(string_agg(" +
     "  n.nspname||'.'||c.relname||'|rls='||c.relrowsecurity" +
     "  ||'|force='||c.relforcerowsecurity, '||' " +
     "  ORDER BY n.nspname, c.relname), '') " +
     "FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace " +
     "WHERE c.relkind IN ('r','p') " +
     "  AND n.nspname NOT IN ('pg_catalog','information_schema','pg_toast')"],
    ["matviews",
     "SELECT COALESCE(string_agg(" +
     "  schemaname||'.'||matviewname||'|'||definition, '||' " +
     "  ORDER BY schemaname, matviewname), '') " +
     "FROM pg_matviews " +
     "WHERE schemaname NOT IN ('pg_catalog','information_schema','pg_toast')"],
    ["function_grants",
     "SELECT COALESCE(string_agg(" +
     "  n.nspname||'.'||p.proname||'('||pg_get_function_identity_arguments(p.oid)||')|'||" +
     "  COALESCE(r.rolname, 'PUBLIC')||'|'||a.privilege_type, '||' " +
     "  ORDER BY n.nspname, p.proname, pg_get_function_identity_arguments(p.oid)," +
     "           r.rolname, a.privilege_type), '') " +
     "FROM pg_proc p " +
     "JOIN pg_namespace n ON n.oid = p.pronamespace " +
     "CROSS JOIN LATERAL aclexplode(COALESCE(p.proacl, acldefault('f', p.proowner))) a " +
     "LEFT JOIN pg_roles r ON r.oid = a.grantee " +
     "WHERE n.nspname NOT IN ('pg_catalog','information_schema','pg_toast')"],
    ["type_grants",
     "SELECT COALESCE(string_agg(" +
     "  n.nspname||'.'||t.typname||'|'||" +
     "  COALESCE(r.rolname, 'PUBLIC')||'|'||a.privilege_type, '||' " +
     "  ORDER BY n.nspname, t.typname, r.rolname, a.privilege_type), '') " +
     "FROM pg_type t " +
     "JOIN pg_namespace n ON n.oid = t.typnamespace " +
     "CROSS JOIN LATERAL aclexplode(COALESCE(t.typacl, acldefault('T', t.typowner))) a " +
     "LEFT JOIN pg_roles r ON r.oid = a.grantee " +
     "WHERE n.nspname NOT IN ('pg_catalog','information_schema','pg_toast')"],
    ["sequence_grants",
     "SELECT COALESCE(string_agg(" +
     "  n.nspname||'.'||c.relname||'|'||" +
     "  COALESCE(r.rolname, 'PUBLIC')||'|'||a.privilege_type, '||' " +
     "  ORDER BY n.nspname, c.relname, r.rolname, a.privilege_type), '') " +
     "FROM pg_class c " +
     "JOIN pg_namespace n ON n.oid = c.relnamespace " +
     "CROSS JOIN LATERAL aclexplode(COALESCE(c.relacl, acldefault('S', c.relowner))) a " +
     "LEFT JOIN pg_roles r ON r.oid = a.grantee " +
     "WHERE c.relkind = 'S' " +
     "  AND n.nspname NOT IN ('pg_catalog','information_schema','pg_toast')"],
    ["default_acl",
     "SELECT COALESCE(string_agg(" +
     "  COALESCE(owner.rolname, 'ALL')||'|'||" +
     "  CASE WHEN d.defaclnamespace = 0 THEN 'ALL' " +
     "       ELSE ns.nspname END||'|'||" +
     "  d.defaclobjtype::text||'|'||" +
     "  COALESCE(grantee.rolname, 'PUBLIC')||'|'||" +
     "  a.privilege_type, '||' " +
     "  ORDER BY COALESCE(owner.rolname, 'ALL'), d.defaclnamespace, " +
     "           d.defaclobjtype::text, COALESCE(grantee.rolname, 'PUBLIC'), " +
     "           a.privilege_type), '') " +
     "FROM pg_default_acl d " +
     "LEFT JOIN pg_roles owner ON owner.oid = d.defaclrole " +
     "LEFT JOIN pg_namespace ns ON ns.oid = d.defaclnamespace " +
     "CROSS JOIN LATERAL aclexplode(d.defaclacl) a " +
     "LEFT JOIN pg_roles grantee ON grantee.oid = a.grantee"],
    ["shared_dependencies",
     // R20-3e: scoped to role references in the current database - this
     // is the surface DROP OWNED BY acts on. Uses numeric OIDs (not
     // ::regclass::text) to avoid "cache lookup failed" errors when a
     // classid references a table that was dropped before snapshot.
     "SELECT COALESCE(string_agg(" +
     "  s.classid::text||'|'||s.objid::text||'|'||" +
     "  s.refclassid::text||'|'||s.refobjid::text||'|'||s.deptype::text" +
     "  , '||' ORDER BY s.classid, s.objid," +
     "           s.refclassid, s.refobjid, s.deptype), '') " +
     "FROM pg_shdepend s " +
     "WHERE s.refclassid = 'pg_authid'::regclass " +
     "  AND (s.dbid = 0 " +
     "       OR s.dbid = (SELECT oid FROM pg_database WHERE datname = current_database()))"],
  ];

  // R20-3b: run all categories in one REPEATABLE READ transaction so
  // every query observes the same committed database snapshot. Script
  // input is required because \echo is a psql meta-command, not SQL.
  const MARK = "__CAT_BOUNDARY_e0d3f4a__";
  const script = [
    "SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;",
    ...queries.map(([label, q]) => `\\echo '${MARK}${label}'\n${q};`),
  ].join("\n");

  const r = spawnSync(
    "psql",
    ["-t", "-A", "-v", "ON_ERROR_STOP=1", "-1", "-f", "-"],
    {
      env,
      input: script,
      encoding: "utf8",
      maxBuffer: 10 * 1024 * 1024,
      timeout: 60_000,
    }
  );

  const stdout = String(r.stdout || "");

  if (r.status !== 0) {
    // The last marker identifies the category executing at failure.
    const idx = stdout.lastIndexOf(MARK);
    const cat =
      idx >= 0
        ? stdout.slice(idx + MARK.length).split("\n")[0].trim()
        : "unknown";
    throw new Error(
      'captureTargetState failed at category "' +
        cat +
        '": ' +
        redactSecrets(String(r.stderr).trim())
    );
  }

  const lines = stdout.split("\n");
  const parts = [];
  let curLabel = null;
  let buf = [];
  const flush = () => {
    if (curLabel !== null) {
      parts.push(curLabel + "=" + buf.join("\n").trim());
    }
  };
  for (const line of lines) {
    if (line.startsWith(MARK)) {
      flush();
      curLabel = line.slice(MARK.length).trim();
      buf = [];
    } else {
      buf.push(line);
    }
  }
  flush();
  return parts.join("\n");
}
const targetStateBefore = captureTargetState(superEnv);
console.log("Negative pre-tests (before setup DDL):");
console.log("  baseline state: captured (27 categories — R20-3 comprehensive snapshot)");
console.log("");

test("R17-3a: missing DISPOSABLE_DB_NAME refused before any DDL", () => {
  let threw = null;
  try {
    assertDisposableTarget(TEST_DATABASE_URL, { expectedDbName: undefined });
  } catch (err) {
    threw = err;
  }
  assertTrue(threw !== null, "guard should refuse when marker is missing");
  const after = captureTargetState(superEnv);
  assertEq(after, targetStateBefore, "target state unchanged after refusal");
});

test("R17-3b: wrong DB name aborts transaction before DDL (state unchanged)", () => {
  const hostileDbName = "hostile-marker-" + Date.now();
  const doBlock = buildDbNameVerificationDoBlock(hostileDbName);
  const hostileAttempt = [
    doBlock,
    "CREATE TABLE __r17_3_hostile_should_not_exist (id int);",
  ].join("\n");
  const r = spawnSync(
    "psql",
    ["-t", "-A", "-v", "ON_ERROR_STOP=1", "-1", "-c", hostileAttempt],
    { env: superEnv, encoding: "utf8", maxBuffer: 1024 * 1024, timeout: 10_000 }
  );
  assertTrue(r.status !== 0, "psql should fail on marker mismatch");
  assertContains(String(r.stderr).toLowerCase(), "disposable db name", "stderr should mention marker");
  const after = captureTargetState(superEnv);
  assertEq(after, targetStateBefore, "target state unchanged — no destructive DDL ran");
});

test("R17-3c: hostile PGHOSTADDR cannot redirect the setup connection", () => {
  const saved = process.env.PGHOSTADDR;
  process.env.PGHOSTADDR = "192.0.2.1"; // TEST-NET-1, unroutable
  try {
    const freshEnv = makePsqlEnv(superUrl);
    const r = spawnSync(
      "psql",
      ["-t", "-A", "-c", "SELECT current_database()"],
      { env: freshEnv, encoding: "utf8", maxBuffer: 1024 * 1024, timeout: 10_000 }
    );
    assertEq(r.status, 0, "psql connected despite hostile ambient");
    assertEq(r.stdout.trim(), EXPECTED_DB_NAME, "connected DB is the disposable DB, not redirected");
    const after = captureTargetState(freshEnv);
    assertEq(after, targetStateBefore, "target state unchanged — env isolation held");
  } finally {
    if (saved === undefined) delete process.env.PGHOSTADDR;
    else process.env.PGHOSTADDR = saved;
  }
});

// ── R19-4: Snapshot self-tests (determinism + detection) ────────
test("R19-4a: snapshot is deterministic (same input → identical output)", () => {
  const a = captureTargetState(superEnv);
  const b = captureTargetState(superEnv);
  assertEq(a, b, "snapshot must be deterministic across two consecutive captures");
});

test("R19-4b: snapshot detects a newly created table and returns to prior state after drop", () => {
  const before = captureTargetState(superEnv);
  const createR = spawnSync(
    "psql",
    ["-t", "-A", "-v", "ON_ERROR_STOP=1", "-c",
     "CREATE TABLE __r19_4_snapshot_sentinel (id int);"],
    { env: superEnv, encoding: "utf8", maxBuffer: 1024 * 1024, timeout: 10_000 }
  );
  assertEq(createR.status, 0, "sentinel table created");
  const during = captureTargetState(superEnv);
  assertTrue(during !== before, "snapshot must detect newly created table");
  const dropR = spawnSync(
    "psql",
    ["-t", "-A", "-v", "ON_ERROR_STOP=1", "-c",
     "DROP TABLE __r19_4_snapshot_sentinel;"],
    { env: superEnv, encoding: "utf8", maxBuffer: 1024 * 1024, timeout: 10_000 }
  );
  assertEq(dropR.status, 0, "sentinel table dropped");
  const after = captureTargetState(superEnv);
  assertEq(after, before, "snapshot returns to prior state after drop");
});

// ── R20-3g: category-specific detection tests ──────────────────
// Expert Round 19 P0-2: previous detection test covered only the
// "tables" category. These tests provide representative detection
// evidence across the remaining category groups. Each test:
//   1. captures baseline snapshot
//   2. applies a targeted mutation (single transaction)
//   3. asserts the snapshot changed AND the specific category
//      contains the expected marker
//   4. reverses the mutation
//   5. asserts the snapshot returns to the baseline state
//
// Categories covered directly: roles, role_attributes, memberships,
// tables, columns, defaults, constraints, indexes, triggers,
// ownership, rls, rls_flags, table_grants, sequence_grants,
// function_grants, type_grants, schema_grants, default_acl,
// db_role_setting, views, matviews, sequences (23 of 27).
//
// Not directly tested (covered by other categories' side effects):
//   row_counts (any CREATE/INSERT changes table counts)
//   row_counts_approx (approximation; not deterministic)
//   shared_dependencies (CREATE ROLE writes pg_shdepend rows)
//   database_grants (would need a second database; scope out)

function extractCategory(snapshot, label) {
  const prefix = label + "=";
  const line = snapshot.split("\n").find((l) => l.startsWith(prefix));
  return line ? line.slice(prefix.length) : "";
}

function psqlTx(sql) {
  return spawnSync(
    "psql",
    ["-t", "-A", "-v", "ON_ERROR_STOP=1", "-1", "-c", sql],
    { env: superEnv, encoding: "utf8", maxBuffer: 10 * 1024 * 1024, timeout: 30_000 }
  );
}

function runCategoryTest(setupSql, dropSql, verifyFn) {
  const before = captureTargetState(superEnv);
  const setup = psqlTx(setupSql);
  assertEq(setup.status, 0, "setup: " + redactSecrets(String(setup.stderr)));
  try {
    const during = captureTargetState(superEnv);
    assertTrue(during !== before, "snapshot must change after setup");
    verifyFn(during);
  } finally {
    const drop = psqlTx(dropSql);
    if (drop.status !== 0) {
      throw new Error("cleanup: " + redactSecrets(String(drop.stderr)));
    }
  }
  const after = captureTargetState(superEnv);
  assertEq(after, before, "snapshot returns to prior state after cleanup");
}

test("R20-3g-A: role lifecycle detected (roles, role_attributes, memberships)", () => {
  const R = "__r20_3g_role_a";
  runCategoryTest(
    `CREATE ROLE "${R}";` +
    `ALTER ROLE "${R}" WITH LOGIN CREATEDB;` +
    `GRANT "${R}" TO CURRENT_USER;`,
    `REVOKE "${R}" FROM CURRENT_USER; DROP ROLE "${R}";`,
    (during) => {
      assertTrue(extractCategory(during, "roles").includes(R), "roles detects");
      assertTrue(extractCategory(during, "role_attributes").includes(R), "role_attributes detects");
      assertTrue(extractCategory(during, "memberships").includes(R), "memberships detects");
    }
  );
});

test("R20-3g-B: table DDL bundle detected (tables, columns, defaults, constraints, indexes, triggers, ownership)", () => {
  const T = "__r20_3g_ddl";
  runCategoryTest(
    `CREATE TABLE public."${T}" (` +
    `  id int PRIMARY KEY,` +
    `  val text DEFAULT 'x'` +
    `);` +
    `CREATE INDEX "${T}_idx" ON public."${T}" (val);` +
    `CREATE TRIGGER "${T}_trg" BEFORE UPDATE ON public."${T}"` +
    `  FOR EACH ROW EXECUTE FUNCTION suppress_redundant_updates_trigger();`,
    `DROP TABLE public."${T}";`,
    (during) => {
      assertTrue(extractCategory(during, "tables").includes(T), "tables detects");
      assertTrue(extractCategory(during, "columns").includes(T), "columns detects");
      assertTrue(extractCategory(during, "defaults").includes(T), "defaults detects");
      assertTrue(extractCategory(during, "constraints").includes(T), "constraints detects");
      assertTrue(extractCategory(during, "indexes").includes(T), "indexes detects");
      assertTrue(extractCategory(during, "triggers").includes(T), "triggers detects");
      assertTrue(extractCategory(during, "ownership").includes(T), "ownership detects");
    }
  );
});

test("R20-3g-C: RLS + policy detected (rls, rls_flags)", () => {
  const T = "__r20_3g_rls";
  runCategoryTest(
    `CREATE TABLE public."${T}" (id int);` +
    `ALTER TABLE public."${T}" ENABLE ROW LEVEL SECURITY;` +
    `CREATE POLICY "${T}_pol" ON public."${T}" FOR SELECT USING (id > 0);`,
    `DROP TABLE public."${T}";`,
    (during) => {
      assertTrue(extractCategory(during, "rls").includes(T), "rls detects");
      assertTrue(extractCategory(during, "rls_flags").includes(T), "rls_flags detects");
      assertTrue(
        extractCategory(during, "rls_flags").includes(T + "|rls=true"),
        "rls_flags shows enabled state"
      );
    }
  );
});

test("R20-3g-D: grants across object types detected (table_grants, column_grants, sequence_grants, function_grants, type_grants, schema_grants, default_acl)", () => {
  const R = "__r20_3g_gr";
  const T = "__r20_3g_gr_tbl";
  const S = "__r20_3g_gr_seq";
  const Y = "__r20_3g_gr_type";
  const F = "__r20_3g_gr_fn";
  runCategoryTest(
    `CREATE ROLE "${R}";` +
    `CREATE TABLE public."${T}" (id int);` +
    `CREATE SEQUENCE public."${S}";` +
    `CREATE TYPE public."${Y}" AS ENUM ('a');` +
    `CREATE FUNCTION public."${F}"() RETURNS int LANGUAGE sql AS $fn$ SELECT 1 $fn$;` +
    `GRANT USAGE ON SCHEMA public TO "${R}";` +
    `GRANT SELECT ON public."${T}" TO "${R}";` +
    `GRANT SELECT (id) ON public."${T}" TO "${R}";` +
    `GRANT USAGE ON SEQUENCE public."${S}" TO "${R}";` +
    `GRANT USAGE ON TYPE public."${Y}" TO "${R}";` +
    `GRANT EXECUTE ON FUNCTION public."${F}"() TO "${R}";` +
    `ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO "${R}";`,
    `DROP TABLE public."${T}";` +
    `DROP SEQUENCE public."${S}";` +
    `DROP TYPE public."${Y}";` +
    `DROP FUNCTION public."${F}"();` +
    `DROP OWNED BY "${R}";` +
    `DROP ROLE "${R}";`,
    (during) => {
      assertTrue(extractCategory(during, "table_grants").includes(R), "table_grants detects");
      assertTrue(extractCategory(during, "column_grants").includes(R), "column_grants detects");
      assertTrue(extractCategory(during, "sequence_grants").includes(R), "sequence_grants detects");
      assertTrue(extractCategory(during, "function_grants").includes(R), "function_grants detects");
      assertTrue(extractCategory(during, "type_grants").includes(R), "type_grants detects");
      assertTrue(extractCategory(during, "schema_grants").includes(R), "schema_grants detects");
      assertTrue(extractCategory(during, "default_acl").includes(R), "default_acl detects");
    }
  );
});

test("R20-3g-E: settings + views + matviews + sequences detected (db_role_setting, views, matviews, sequences)", () => {
  const R = "__r20_3g_set_r";
  const SRC = "__r20_3g_src";
  const V = "__r20_3g_view";
  const M = "__r20_3g_matview";
  const Q = "__r20_3g_seq";
  runCategoryTest(
    `CREATE ROLE "${R}";` +
    `ALTER ROLE "${R}" IN DATABASE "${EXPECTED_DB_NAME}" SET statement_timeout = '7s';` +
    `CREATE TABLE public."${SRC}" (id int);` +
    `CREATE VIEW public."${V}" AS SELECT id FROM public."${SRC}";` +
    `CREATE MATERIALIZED VIEW public."${M}" AS SELECT 1 AS x;` +
    `CREATE SEQUENCE public."${Q}";`,
    `DROP VIEW public."${V}";` +
    `DROP MATERIALIZED VIEW public."${M}";` +
    `DROP SEQUENCE public."${Q}";` +
    `DROP TABLE public."${SRC}";` +
    `DROP OWNED BY "${R}";` +
    `DROP ROLE "${R}";`,
    (during) => {
      assertTrue(extractCategory(during, "db_role_setting").includes(R), "db_role_setting detects");
      assertTrue(extractCategory(during, "views").includes(V), "views detects");
      assertTrue(extractCategory(during, "matviews").includes(M), "matviews detects");
      assertTrue(extractCategory(during, "sequences").includes(Q), "sequences detects");
    }
  );
});

// ── Setup (as superuser) ────────────────────────────────────────
// R17-2: DB name verification and destructive DDL are folded into a SINGLE
// psql -c invocation with `-1` (single transaction) and `ON_ERROR_STOP=1`.
// If the DB name DO block raises, the transaction is aborted before any
// DDL statement runs. This eliminates the target-switch / second-connection
// gap flagged in Round 16 review (P0 #2): the connection that attests the
// disposable database name is the same connection that executes the DDL.
const dbNameDoBlock = buildDbNameVerificationDoBlock(EXPECTED_DB_NAME);
const clusterDoBlock = buildClusterVerificationDoBlock(TRUSTED_CLUSTER_ID);

const setupSql = [
  dbNameDoBlock,
  clusterDoBlock,
  `DROP TABLE IF EXISTS ${TEST_TABLE};`,
  `CREATE ROLE ${ROLE_NAME} LOGIN PASSWORD '${ROLE_PASSWORD}';`,
  `CREATE TABLE ${TEST_TABLE} (id int);`,
  `GRANT SELECT, INSERT ON ${TEST_TABLE} TO ${ROLE_NAME};`,
].join("\n");

// R20-1d: fail-closed if role already exists.
// Per-run names are unique by design, but if a collision occurs,
// DROP ROLE would be destructive (cascades via DROP OWNED). Abort
// instead of silently cleaning up.
const roleExistsCheck = spawnSync(
  "psql",
  ["-t", "-A", "-c", `SELECT 1 FROM pg_roles WHERE rolname = '${ROLE_NAME}'`],
  { env: superEnv, encoding: "utf8", maxBuffer: 1024 * 1024, timeout: 10_000 }
);
if (roleExistsCheck.status !== 0) {
  console.error("FAIL: cannot query pg_roles:");
  console.error(redactSecrets(roleExistsCheck.stderr));
  process.exit(1);
}
if (roleExistsCheck.stdout.trim() === "1") {
  console.error(`FAIL-CLOSED: role ${ROLE_NAME} already exists on this cluster.`);
  console.error("Refusing to DROP (would cascade). Aborting to preserve fail-closed semantics.");
  process.exit(1);
}

const setup = spawnSync(
  "psql",
  ["-t", "-A", "-F", "\t", "-v", "ON_ERROR_STOP=1", "-1", "-c", setupSql],
  { env: superEnv, encoding: "utf8", maxBuffer: 10 * 1024 * 1024, timeout: 30_000 }
);
if (setup.status !== 0) {
  console.error("SETUP FAILED:");
  console.error(redactSecrets(setup.stderr));
  process.exit(1);
}

// ── N-a: BEGIN READ ONLY produces no stdout noise ───────────────────────
test("N-a: BEGIN READ ONLY; SELECT 1; COMMIT; produces just '1'", () => {
  const r = psql("SELECT 1 AS n");
  assertEq(r.status, 0, "exit code");
  assertEq(r.stdout.trim(), "1", "stdout");
  assertTrue(!r.stdout.includes("BEGIN"), "no BEGIN in stdout");
  assertTrue(!r.stdout.includes("COMMIT"), "no COMMIT in stdout");
});

// ── N-b: Multiple columns tab-separated (real psql -F \t) ───────────────
test("N-b: multiple columns are tab-separated", () => {
  const r = psql("SELECT 'a' AS x, 'b' AS y, 42 AS z");
  assertEq(r.status, 0, "exit code");
  assertEq(r.stdout.trim(), "a\tb\t42", "stdout");
});

// ── N-c: Role check query with guard opt-out (ambient state) ────────────
test("N-c: role check query works with guard opt-out", () => {
  const r = psql(
    "SELECT current_user, session_user, current_setting('transaction_read_only')",
    { guard: false }
  );
  assertEq(r.status, 0, "exit code");
  const parts = r.stdout.trim().split("\t");
  assertEq(parts.length, 3, "column count");
  assertEq(parts[0], parts[1], "current_user === session_user");
  assertTrue(["on", "off"].includes(parts[2]), `read_only value: ${parts[2]}`);
});

// ── N-d: SHOW search_path produces expected format ──────────────────────
test("N-d: SHOW search_path returns a string containing 'public'", () => {
  const r = psql("SHOW search_path");
  assertEq(r.status, 0, "exit code");
  assertContains(r.stdout, "public", "stdout");
});

// ── N-e: Error propagation — invalid SQL returns non-zero exit ──────────
test("N-e: invalid SQL returns non-zero exit + stderr", () => {
  const r = psql("SELECT * FROM table_that_does_not_exist_r13");
  assertTrue(r.status !== 0, "exit code should be non-zero");
  assertContains(
    r.stderr.toLowerCase(),
    "does not exist",
    "stderr should mention 'does not exist'"
  );
});

// ── N-f: Read-only enforcement — INSERT WITH guard FAILS ────────────────
test("N-f: INSERT inside BEGIN READ ONLY fails as non-superuser role", () => {
  const r = psql(
    `INSERT INTO ${TEST_TABLE} VALUES (100)`,
    { guard: true, env: roEnv }
  );
  assertTrue(r.status !== 0, "exit code should be non-zero");
  assertContains(
    r.stderr.toLowerCase(),
    "read-only",
    "stderr should mention 'read-only'"
  );
});

// ── N-g: Same INSERT WITHOUT guard SUCCEEDS (proves privilege) ──────────
test("N-g: same INSERT without guard succeeds (role has INSERT privilege)", () => {
  const r = psql(
    `INSERT INTO ${TEST_TABLE} VALUES (200)`,
    { guard: false, env: roEnv }
  );
  assertEq(r.status, 0, "exit code");
});

// ── N-h: SELECT in guard mode as non-superuser role ─────────────────────
test("N-h: SELECT inside guard mode works for readonly role", () => {
  const r = psql(`SELECT COUNT(*) FROM ${TEST_TABLE}`, { env: roEnv });
  assertEq(r.status, 0, "exit code");
  const count = Number(r.stdout.trim());
  assertTrue(count >= 1, `count >= 1 (got ${count})`);
});

// ── R16-2: Hostile ambient override must not redirect the connection ──
test("N-i: hostile ambient PGHOSTADDR is stripped (env isolation)", () => {
  const saved = process.env.PGHOSTADDR;
  process.env.PGHOSTADDR = "192.0.2.1"; // TEST-NET-1, guaranteed unroutable
  try {
    const freshEnv = makePsqlEnv(superUrl);
    assertTrue(
      freshEnv.PGHOSTADDR === undefined,
      "PGHOSTADDR must NOT propagate to psql env (fail-closed isolation)"
    );
  } finally {
    if (saved === undefined) delete process.env.PGHOSTADDR;
    else process.env.PGHOSTADDR = saved;
  }
});

test("N-j: hostile ambient PGHOSTADDR does not redirect psql (integration)", () => {
  const saved = process.env.PGHOSTADDR;
  process.env.PGHOSTADDR = "192.0.2.1"; // TEST-NET-1, unroutable
  try {
    // Rebuild env fresh with hostile ambient in place.
    const freshEnv = makePsqlEnv(superUrl);
    // If PGHOSTADDR leaked, psql would try 192.0.2.1 and time out.
    // Success proves override was blocked before the connection.
    const r = spawnSync("psql", ["-t", "-A", "-c", "SELECT 1 AS n"], {
      env: freshEnv, encoding: "utf8", timeout: 10_000,
    });
    assertEq(r.status, 0, "psql succeeded against correct target (override blocked)");
    assertEq(r.stdout.trim(), "1", "stdout");
  } finally {
    if (saved === undefined) delete process.env.PGHOSTADDR;
    else process.env.PGHOSTADDR = saved;
  }
});

// ── R19-5: Exact-path wrong-identity tests for cleanup ────────
// Expert Round 18 (P0 Blocker #3):
//   "Real-psql test reduced copied cleanup sequence chalata hai.
//    Actual production cleanup mein REVOKE, DROP OWNED aur DROP ROLE
//    ka different sequence hai. Missing-identity test sirf guard call
//    karta hai; actual cleanup attempt nahi karta."
//
// These tests exercise the EXACT production cleanup path via the shared
// runner (scripts/audit/cleanup-runner.mjs), not a reduced copy. Each
// case proves complete unchanged state via the V2 comprehensive snapshot.

const targetStateBeforeCleanup = captureTargetState(superEnv);
console.log("\nR19-5: Cleanup wrong-identity tests (exact production path):\n");

test("R19-5a: wrong DB name aborts before any REVOKE/DROP (state unchanged)", () => {
  const wrongDbName = "audit_wrong_" + Date.now();
  const wrongGuard = buildCleanupGuard({
    expectedDbName: wrongDbName,
    expectedClusterId: TRUSTED_CLUSTER_ID,
  });
  const cleanupSql = buildCleanupSequence({
    roleName: ROLE_NAME,
    dbName: EXPECTED_DB_NAME,
    tableNames: [TEST_TABLE],
    guardDoBlocks: wrongGuard,
  });
  const r = spawnSync(
    "psql",
    ["-t", "-A", "-F", "\t", "-v", "ON_ERROR_STOP=1", "-1", "-c", cleanupSql],
    { env: superEnv, encoding: "utf8", maxBuffer: 10 * 1024 * 1024, timeout: 30_000 }
  );
  assertTrue(r.status !== 0, "psql should fail on DB name mismatch");
  assertContains(
    String(r.stderr).toLowerCase(),
    "disposable db name mismatch",
    "stderr should mention mismatch"
  );
  const after = captureTargetState(superEnv);
  assertEq(after, targetStateBeforeCleanup, "state unchanged - no REVOKE/DROP ran");
});

test("R19-5b: missing role identity refuses before DDL (state unchanged)", () => {
  const guard = buildCleanupGuard({
    expectedDbName: EXPECTED_DB_NAME,
    expectedClusterId: TRUSTED_CLUSTER_ID,
  });
  let threw = null;
  try {
    buildCleanupSequence({
      roleName: undefined,
      dbName: EXPECTED_DB_NAME,
      tableNames: [TEST_TABLE],
      guardDoBlocks: guard,
    });
  } catch (err) {
    threw = err;
  }
  assertTrue(threw !== null, "buildCleanupSequence must refuse missing roleName");
  // No SQL was emitted, so no DDL ran.
  const after = captureTargetState(superEnv);
  assertEq(after, targetStateBeforeCleanup, "state unchanged - no DDL emitted");
});

test("R19-5c: wrong cluster ID aborts before any REVOKE/DROP (state unchanged)", () => {
  const wrongClusterId = (BigInt(TRUSTED_CLUSTER_ID) ^ 1n).toString();
  const wrongGuard = buildCleanupGuard({
    expectedDbName: EXPECTED_DB_NAME,
    expectedClusterId: wrongClusterId,
  });
  const cleanupSql = buildCleanupSequence({
    roleName: ROLE_NAME,
    dbName: EXPECTED_DB_NAME,
    tableNames: [TEST_TABLE],
    guardDoBlocks: wrongGuard,
  });
  const r = spawnSync(
    "psql",
    ["-t", "-A", "-F", "\t", "-v", "ON_ERROR_STOP=1", "-1", "-c", cleanupSql],
    { env: superEnv, encoding: "utf8", maxBuffer: 10 * 1024 * 1024, timeout: 30_000 }
  );
  assertTrue(r.status !== 0, "psql should fail on cluster mismatch");
  assertContains(
    String(r.stderr).toLowerCase(),
    "cluster mismatch",
    "stderr should mention cluster mismatch"
  );
  const after = captureTargetState(superEnv);
  assertEq(after, targetStateBeforeCleanup, "state unchanged - no REVOKE/DROP ran");
});

test("R19-1a: wrong cluster + matching DB name aborts before DDL (state unchanged)", () => {
  // Wrong cluster ID: flip the last bit of the trusted ID via XOR 1.
  // Guarantees a distinct value regardless of the actual ID.
  const wrongClusterId = (BigInt(TRUSTED_CLUSTER_ID) ^ 1n).toString();
  const wrongClusterDoBlock = buildClusterVerificationDoBlock(wrongClusterId);
  const hostileAttempt = [
    wrongClusterDoBlock,
    "CREATE TABLE __r19_1_should_not_exist (id int);",
  ].join("\n");
  const r = spawnSync(
    "psql",
    ["-t", "-A", "-v", "ON_ERROR_STOP=1", "-1", "-c", hostileAttempt],
    { env: superEnv, encoding: "utf8", maxBuffer: 10 * 1024 * 1024, timeout: 10_000 }
  );
  assertTrue(r.status !== 0, "psql should fail on cluster mismatch");
  assertContains(String(r.stderr).toLowerCase(), "cluster mismatch", "stderr should mention cluster mismatch");
  const after = captureTargetState(superEnv);
  assertEq(after, targetStateBeforeCleanup, "state unchanged — no DDL ran");
});

test("R20-1c: independent-source cluster ID mismatch aborts before DDL", () => {
  // R20-1c: Threat model — pg_controldata (filesystem read) captured a
  // legitimate cluster ID, but the container was swapped between capture
  // and DDL. The stored ID is self-consistent (it was really captured),
  // yet does not match the actual mutation target. Verification via
  // pg_control_system() must still abort.
  const independentWrongId = (BigInt(TRUSTED_CLUSTER_ID) + 9999999999n).toString();
  const wrongGuard = buildClusterVerificationDoBlock(independentWrongId);
  const attempt = [
    wrongGuard,
    "CREATE TABLE __r20_1c_should_not_exist (id int);",
  ].join("\n");
  const r = spawnSync(
    "psql",
    ["-t", "-A", "-v", "ON_ERROR_STOP=1", "-1", "-c", attempt],
    { env: superEnv, encoding: "utf8", maxBuffer: 10 * 1024 * 1024, timeout: 10_000 }
  );
  assertTrue(r.status !== 0, "psql should fail on wrong cluster ID");
  assertContains(
    String(r.stderr).toLowerCase(),
    "cluster mismatch",
    "stderr should mention cluster mismatch"
  );
  // Cleanup sentinel if by some bug it was created
  spawnSync(
    "psql",
    ["-t", "-A", "-c", "DROP TABLE IF EXISTS __r20_1c_should_not_exist"],
    { env: superEnv, encoding: "utf8", timeout: 10_000 }
  );
});

// ── Cleanup (as superuser) ──────────────────────────────────────────────
// R18-1: cleanup also fails-closed through the same guarded pattern as
// setup. DB name DO block + DROP statements combined in a single psql -1
// -v ON_ERROR_STOP=1 transaction. On marker mismatch the transaction
// aborts before any DROP statement runs — closing the R17 cleanup gap.
const cleanupDbNameDoBlock = buildDbNameVerificationDoBlock(EXPECTED_DB_NAME);
const cleanupClusterDoBlock = buildClusterVerificationDoBlock(TRUSTED_CLUSTER_ID);
const cleanupSql = [
  cleanupDbNameDoBlock,
  cleanupClusterDoBlock,
  `DROP TABLE IF EXISTS ${TEST_TABLE};`,
  `DROP ROLE IF EXISTS ${ROLE_NAME};`,
].join("\n");
const cleanupResult = spawnSync(
  "psql",
  ["-t", "-A", "-F", "\t", "-v", "ON_ERROR_STOP=1", "-1", "-c", cleanupSql],
  { env: superEnv, encoding: "utf8", maxBuffer: 10 * 1024 * 1024, timeout: 30_000 }
);
if (cleanupResult.status !== 0) {
  console.error("CLEANUP FAILED:");
  console.error(redactSecrets(cleanupResult.stderr));
  process.exit(1);
}

console.log(`\n${passed} passed, ${failed} failed\n`);
process.exit(failed > 0 ? 1 : 0);
