#!/usr/bin/env node
// ============================================================================
// Real psql integration test — Round 13 R13-2
// ============================================================================
// Purpose:
//   Expert feedback: "Mock tests real psql output represent nahi karte.
//   BEGIN/COMMIT ke saath actual psql output aur error behaviour ko
//   disposable, non-production database par validate karein."
//
// Approach:
//   - Uses a disposable PostgreSQL instance (postgres:16 in CI).
//   - Sets up a dedicated NON-superuser role (superuser bypasses
//     BEGIN READ ONLY enforcement — production uses non-superuser).
//   - Runs real psql invocations with BEGIN READ ONLY; ...; COMMIT;
//     wrappers exactly as the harness does.
//   - Validates actual stdout/stderr/exit-code behavior.
//
// Local dev behavior:
//   - If TEST_DATABASE_URL is not set, the test SKIPS (exit 0).
//   - No local PostgreSQL required.
// ============================================================================

import { spawnSync } from "node:child_process";
import {
  assertDisposableTarget,
  buildDbNameVerificationDoBlock,
  buildClusterVerificationDoBlock,
} from "./disposable-target-guard.mjs";

const TEST_DATABASE_URL = process.env.TEST_DATABASE_URL;

if (!TEST_DATABASE_URL) {
  console.log("\nSKIP: TEST_DATABASE_URL not set (local dev / no DB).\n");
  process.exit(0);
}

// Round 15 R15-1: refuse destructive DDL against non-disposable targets.
// Must be called BEFORE any DROP/CREATE statement. Fail-closed.
// Round 17 R17-1: disposable-target identity is proven by a per-run marker
// injected by the CI workflow. Network-address classification is removed.
const EXPECTED_DB_NAME = process.env.DISPOSABLE_DB_NAME;
assertDisposableTarget(TEST_DATABASE_URL, { expectedDbName: EXPECTED_DB_NAME });

// R19-1: cluster identity binding — independently trusted anchor for
// the mutation target. system_identifier is captured by the CI workflow
// before the test runs, is immutable per cluster, and is verified in the
// SAME transaction as the DDL (setup and cleanup).
const TRUSTED_CLUSTER_ID = process.env.TRUSTED_CLUSTER_ID;
if (!TRUSTED_CLUSTER_ID) {
  console.error("TRUSTED_CLUSTER_ID: not set. Refusing to proceed.");
  process.exit(1);
}

// ── Setup: derive superuser + readonly role URLs ────────────────────────
const superUrl = new URL(TEST_DATABASE_URL);

// R19-2: per-run role name. PostgreSQL roles are cluster-wide, so a
// fixed name would be shared across runs, attempts, and clusters —
// unsafe for cleanup (DROP ROLE) and untraceable to this run. The name
// is generated by the CI workflow before the test runs and is validated
// here against the expected pattern (defence in depth).
const ROLE_NAME = process.env.TEST_ROLE_NAME;
if (!ROLE_NAME) {
  console.error("TEST_ROLE_NAME: not set. Refusing to proceed.");
  process.exit(1);
}
if (!/^audit_ro_[0-9]+_[0-9]+_[a-f0-9]+$/.test(ROLE_NAME)) {
  console.error("TEST_ROLE_NAME: unexpected format: " + ROLE_NAME);
  process.exit(1);
}
const ROLE_PASSWORD = ROLE_NAME + "_pass";

const roUrl = new URL(TEST_DATABASE_URL);
roUrl.username = ROLE_NAME;
roUrl.password = ROLE_PASSWORD;

const TEST_TABLE = "test_r13_readonly_enforcement";

// ── psql runner (mirrors harness: -t -A -F \t + optional BEGIN READ ONLY) ──
// R16-1: Fail-closed env isolation (mirrors notification-inventory.mjs R14-1).
// Ambient PG* vars are NEVER inherited — only an explicit operational allowlist
// plus the URL-derived PG* values. Prevents PGHOSTADDR/PGSERVICE/PGOPTIONS/etc.
// from overriding the URL target after assertDisposableTarget() has passed.
const SAFE_PASSTHROUGH = [
  "PATH", "Path", "HOME", "LANG", "LC_ALL", "LC_MESSAGES",
  "TZ", "TERM", "USER", "LOGNAME", "SHELL",
];

function makePsqlEnv(urlObj) {
  const env = {};
  for (const key of SAFE_PASSTHROUGH) {
    if (process.env[key] !== undefined) {
      env[key] = process.env[key];
    }
  }
  env.PGPASSWORD = decodeURIComponent(urlObj.password);
  env.PGUSER = decodeURIComponent(urlObj.username);
  env.PGHOST = urlObj.hostname;
  env.PGPORT = urlObj.port || "5432";
  env.PGDATABASE = urlObj.pathname.replace(/^\//, "");
  env.PGSSLMODE = "prefer";
  return env;
}

const superEnv = makePsqlEnv(superUrl);
const roEnv = makePsqlEnv(roUrl);

function psql(sql, { guard = true, env = superEnv } = {}) {
  // Semicolon after ${sql} required — see R13-2b.
  const guardedSql = guard ? `BEGIN READ ONLY;\n${sql};\nCOMMIT;` : sql;
  const result = spawnSync(
    "psql",
    ["-t", "-A", "-F", "\t", "-c", guardedSql],
    { env, encoding: "utf8", maxBuffer: 10 * 1024 * 1024, timeout: 30_000 }
  );
  // R13-2c: mirror harness — strip BEGIN/COMMIT command tags.
  if (guard && typeof result.stdout === "string") {
    result.stdout = result.stdout
      .split("\n")
      .filter((line) => line !== "BEGIN" && line !== "COMMIT")
      .join("\n");
  }
  return result;
}

// ── Test harness ────────────────────────────────────────────────────────
let passed = 0;
let failed = 0;

function test(name, fn) {
  try {
    fn();
    console.log(`  ✓ ${name}`);
    passed++;
  } catch (err) {
    console.error(`  ✗ ${name}`);
    console.error(`    ${err.message}`);
    failed++;
  }
}

function assertEq(actual, expected, label) {
  if (actual !== expected) {
    throw new Error(
      `${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`
    );
  }
}

function assertTrue(cond, label) {
  if (!cond) throw new Error(`${label}: expected true`);
}

function assertContains(haystack, needle, label) {
  if (!haystack.includes(needle)) {
    throw new Error(
      `${label}: expected to contain ${JSON.stringify(needle)}, got: ${haystack.slice(0, 400)}`
    );
  }
}

console.log("\nReal psql integration tests (Round 13 R13-2):\n");
// ── R17-3: Negative pre-tests — run BEFORE any real DDL ────────
// Expert Round 16 concern (P0 #3): "Negative test setup DDL se pehle
// hostile/non-disposable target introduce kare aur prove kare ke zero
// destructive statements chalin aur known target state unchanged rahi."

// Helper: comprehensive snapshot of the target database state.
// R18-3: capture ALL non-system state that destructive DDL could touch —
// tables, roles, grants, and column definitions — not just public table
// names. The snapshot is a deterministic, ordered string that can be
// compared before/after each negative-path test.
function captureTargetState(env) {
  const queries = [
    ["tables",
     "SELECT COALESCE(string_agg(schemaname||'.'||tablename, '|' ORDER BY 1), '') " +
     "FROM pg_tables WHERE schemaname NOT IN ('pg_catalog','information_schema')"],
    ["roles",
     "SELECT COALESCE(string_agg(rolname, '|' ORDER BY 1), '') " +
     "FROM pg_roles WHERE rolname NOT LIKE 'pg_%'"],
    ["grants",
     "SELECT COALESCE(string_agg(table_schema||'.'||table_name||':'||grantee||':'||privilege_type, '|' ORDER BY 1), '') " +
     "FROM information_schema.role_table_grants " +
     "WHERE table_schema NOT IN ('pg_catalog','information_schema')"],
    ["columns",
     "SELECT COALESCE(string_agg(table_schema||'.'||table_name||'.'||column_name||':'||data_type, '|' ORDER BY 1), '') " +
     "FROM information_schema.columns " +
     "WHERE table_schema NOT IN ('pg_catalog','information_schema')"],
  ];
  const parts = [];
  for (const [label, q] of queries) {
    const r = spawnSync(
      "psql",
      ["-t", "-A", "-c", q],
      { env, encoding: "utf8", maxBuffer: 10 * 1024 * 1024, timeout: 10_000 }
    );
    if (r.status !== 0) {
      throw new Error("captureTargetState(" + label + ") failed: " + String(r.stderr).trim());
    }
    parts.push(label + "=" + r.stdout.trim());
  }
  return parts.join("\\n");
}
const targetStateBefore = captureTargetState(superEnv);
console.log("Negative pre-tests (before setup DDL):");
console.log("  baseline state: captured (tables + roles + grants + columns)");
console.log("");

test("R17-3a: missing DISPOSABLE_DB_NAME refused before any DDL", () => {
  let threw = null;
  try {
    assertDisposableTarget(TEST_DATABASE_URL, { expectedDbName: undefined });
  } catch (err) {
    threw = err;
  }
  assertTrue(threw !== null, "guard should refuse when marker is missing");
  const after = captureTargetState(superEnv);
  assertEq(after, targetStateBefore, "target state unchanged after refusal");
});

test("R17-3b: wrong DB name aborts transaction before DDL (state unchanged)", () => {
  const hostileDbName = "hostile-marker-" + Date.now();
  const doBlock = buildDbNameVerificationDoBlock(hostileDbName);
  const hostileAttempt = [
    doBlock,
    "CREATE TABLE __r17_3_hostile_should_not_exist (id int);",
  ].join("\n");
  const r = spawnSync(
    "psql",
    ["-t", "-A", "-v", "ON_ERROR_STOP=1", "-1", "-c", hostileAttempt],
    { env: superEnv, encoding: "utf8", maxBuffer: 1024 * 1024, timeout: 10_000 }
  );
  assertTrue(r.status !== 0, "psql should fail on marker mismatch");
  assertContains(String(r.stderr).toLowerCase(), "disposable db name", "stderr should mention marker");
  const after = captureTargetState(superEnv);
  assertEq(after, targetStateBefore, "target state unchanged — no destructive DDL ran");
});

test("R17-3c: hostile PGHOSTADDR cannot redirect the setup connection", () => {
  const saved = process.env.PGHOSTADDR;
  process.env.PGHOSTADDR = "192.0.2.1"; // TEST-NET-1, unroutable
  try {
    const freshEnv = makePsqlEnv(superUrl);
    const r = spawnSync(
      "psql",
      ["-t", "-A", "-c", "SELECT current_database()"],
      { env: freshEnv, encoding: "utf8", maxBuffer: 1024 * 1024, timeout: 10_000 }
    );
    assertEq(r.status, 0, "psql connected despite hostile ambient");
    assertEq(r.stdout.trim(), EXPECTED_DB_NAME, "connected DB is the disposable DB, not redirected");
    const after = captureTargetState(freshEnv);
    assertEq(after, targetStateBefore, "target state unchanged — env isolation held");
  } finally {
    if (saved === undefined) delete process.env.PGHOSTADDR;
    else process.env.PGHOSTADDR = saved;
  }
});


// ── Setup (as superuser) ────────────────────────────────────────
// R17-2: DB name verification and destructive DDL are folded into a SINGLE
// psql -c invocation with `-1` (single transaction) and `ON_ERROR_STOP=1`.
// If the DB name DO block raises, the transaction is aborted before any
// DDL statement runs. This eliminates the target-switch / second-connection
// gap flagged in Round 16 review (P0 #2): the connection that attests the
// disposable database name is the same connection that executes the DDL.
const dbNameDoBlock = buildDbNameVerificationDoBlock(EXPECTED_DB_NAME);
const clusterDoBlock = buildClusterVerificationDoBlock(TRUSTED_CLUSTER_ID);

const setupSql = [
  dbNameDoBlock,
  clusterDoBlock,
  `DROP TABLE IF EXISTS ${TEST_TABLE};`,
  `DROP ROLE IF EXISTS ${ROLE_NAME};`,
  `CREATE ROLE ${ROLE_NAME} LOGIN PASSWORD '${ROLE_PASSWORD}';`,
  `CREATE TABLE ${TEST_TABLE} (id int);`,
  `GRANT SELECT, INSERT ON ${TEST_TABLE} TO ${ROLE_NAME};`,
].join("\n");

const setup = spawnSync(
  "psql",
  ["-t", "-A", "-F", "\t", "-v", "ON_ERROR_STOP=1", "-1", "-c", setupSql],
  { env: superEnv, encoding: "utf8", maxBuffer: 10 * 1024 * 1024, timeout: 30_000 }
);
if (setup.status !== 0) {
  console.error("SETUP FAILED:");
  console.error(setup.stderr);
  process.exit(1);
}

// ── N-a: BEGIN READ ONLY produces no stdout noise ───────────────────────
test("N-a: BEGIN READ ONLY; SELECT 1; COMMIT; produces just '1'", () => {
  const r = psql("SELECT 1 AS n");
  assertEq(r.status, 0, "exit code");
  assertEq(r.stdout.trim(), "1", "stdout");
  assertTrue(!r.stdout.includes("BEGIN"), "no BEGIN in stdout");
  assertTrue(!r.stdout.includes("COMMIT"), "no COMMIT in stdout");
});

// ── N-b: Multiple columns tab-separated (real psql -F \t) ───────────────
test("N-b: multiple columns are tab-separated", () => {
  const r = psql("SELECT 'a' AS x, 'b' AS y, 42 AS z");
  assertEq(r.status, 0, "exit code");
  assertEq(r.stdout.trim(), "a\tb\t42", "stdout");
});

// ── N-c: Role check query with guard opt-out (ambient state) ────────────
test("N-c: role check query works with guard opt-out", () => {
  const r = psql(
    "SELECT current_user, session_user, current_setting('transaction_read_only')",
    { guard: false }
  );
  assertEq(r.status, 0, "exit code");
  const parts = r.stdout.trim().split("\t");
  assertEq(parts.length, 3, "column count");
  assertEq(parts[0], parts[1], "current_user === session_user");
  assertTrue(["on", "off"].includes(parts[2]), `read_only value: ${parts[2]}`);
});

// ── N-d: SHOW search_path produces expected format ──────────────────────
test("N-d: SHOW search_path returns a string containing 'public'", () => {
  const r = psql("SHOW search_path");
  assertEq(r.status, 0, "exit code");
  assertContains(r.stdout, "public", "stdout");
});

// ── N-e: Error propagation — invalid SQL returns non-zero exit ──────────
test("N-e: invalid SQL returns non-zero exit + stderr", () => {
  const r = psql("SELECT * FROM table_that_does_not_exist_r13");
  assertTrue(r.status !== 0, "exit code should be non-zero");
  assertContains(
    r.stderr.toLowerCase(),
    "does not exist",
    "stderr should mention 'does not exist'"
  );
});

// ── N-f: Read-only enforcement — INSERT WITH guard FAILS ────────────────
test("N-f: INSERT inside BEGIN READ ONLY fails as non-superuser role", () => {
  const r = psql(
    `INSERT INTO ${TEST_TABLE} VALUES (100)`,
    { guard: true, env: roEnv }
  );
  assertTrue(r.status !== 0, "exit code should be non-zero");
  assertContains(
    r.stderr.toLowerCase(),
    "read-only",
    "stderr should mention 'read-only'"
  );
});

// ── N-g: Same INSERT WITHOUT guard SUCCEEDS (proves privilege) ──────────
test("N-g: same INSERT without guard succeeds (role has INSERT privilege)", () => {
  const r = psql(
    `INSERT INTO ${TEST_TABLE} VALUES (200)`,
    { guard: false, env: roEnv }
  );
  assertEq(r.status, 0, "exit code");
});

// ── N-h: SELECT in guard mode as non-superuser role ─────────────────────
test("N-h: SELECT inside guard mode works for readonly role", () => {
  const r = psql(`SELECT COUNT(*) FROM ${TEST_TABLE}`, { env: roEnv });
  assertEq(r.status, 0, "exit code");
  const count = Number(r.stdout.trim());
  assertTrue(count >= 1, `count >= 1 (got ${count})`);
});

// ── R16-2: Hostile ambient override must not redirect the connection ──
test("N-i: hostile ambient PGHOSTADDR is stripped (env isolation)", () => {
  const saved = process.env.PGHOSTADDR;
  process.env.PGHOSTADDR = "192.0.2.1"; // TEST-NET-1, guaranteed unroutable
  try {
    const freshEnv = makePsqlEnv(superUrl);
    assertTrue(
      freshEnv.PGHOSTADDR === undefined,
      "PGHOSTADDR must NOT propagate to psql env (fail-closed isolation)"
    );
  } finally {
    if (saved === undefined) delete process.env.PGHOSTADDR;
    else process.env.PGHOSTADDR = saved;
  }
});

test("N-j: hostile ambient PGHOSTADDR does not redirect psql (integration)", () => {
  const saved = process.env.PGHOSTADDR;
  process.env.PGHOSTADDR = "192.0.2.1"; // TEST-NET-1, unroutable
  try {
    // Rebuild env fresh with hostile ambient in place.
    const freshEnv = makePsqlEnv(superUrl);
    // If PGHOSTADDR leaked, psql would try 192.0.2.1 and time out.
    // Success proves override was blocked before the connection.
    const r = spawnSync("psql", ["-t", "-A", "-c", "SELECT 1 AS n"], {
      env: freshEnv, encoding: "utf8", timeout: 10_000,
    });
    assertEq(r.status, 0, "psql succeeded against correct target (override blocked)");
    assertEq(r.stdout.trim(), "1", "stdout");
  } finally {
    if (saved === undefined) delete process.env.PGHOSTADDR;
    else process.env.PGHOSTADDR = saved;
  }
});

// ── R18-4: Wrong-identity tests for cleanup sequence ─────────
// Expert Round 17 (Checkpoint 3): actual cleanup sequence ke wrong-identity
// tests do. Setup sequence wrong-identity tests are R17-3a/b/c above.
// These tests verify the cleanup guard fails-closed BEFORE any DROP, using
// the comprehensive snapshot (R18-3) as evidence of unchanged state.

const targetStateBeforeCleanup = captureTargetState(superEnv);
console.log("\nR18-4: Cleanup wrong-identity tests:\n");

test("R18-4a: cleanup with wrong DB_NAME aborts before DROP (state unchanged)", () => {
  const wrongDbName = "audit_wrong_" + Date.now();
  const wrongDoBlock = buildDbNameVerificationDoBlock(wrongDbName);
  const wrongCleanupSql = [
    wrongDoBlock,
    `DROP TABLE IF EXISTS ${TEST_TABLE};`,
    `DROP ROLE IF EXISTS ${ROLE_NAME};`,
  ].join("\n");
  const r = spawnSync(
    "psql",
    ["-t", "-A", "-F", "\t", "-v", "ON_ERROR_STOP=1", "-1", "-c", wrongCleanupSql],
    { env: superEnv, encoding: "utf8", maxBuffer: 10 * 1024 * 1024, timeout: 10_000 }
  );
  assertTrue(r.status !== 0, "psql should fail on DB name mismatch");
  assertContains(String(r.stderr).toLowerCase(), "disposable db name mismatch", "stderr should mention mismatch");
  const after = captureTargetState(superEnv);
  assertEq(after, targetStateBeforeCleanup, "state unchanged \u2014 no DROP ran");
});

test("R18-4b: missing DISPOSABLE_DB_NAME refused before any DDL", () => {
  let threw = null;
  try {
    assertDisposableTarget(TEST_DATABASE_URL, { expectedDbName: undefined });
  } catch (err) {
    threw = err;
  }
  assertTrue(threw !== null, "guard should refuse when DB name is missing");
  const after = captureTargetState(superEnv);
  assertEq(after, targetStateBeforeCleanup, "state unchanged after refusal");
});

test("R19-1a: wrong cluster + matching DB name aborts before DDL (state unchanged)", () => {
  // Wrong cluster ID: flip the last bit of the trusted ID via XOR 1.
  // Guarantees a distinct value regardless of the actual ID.
  const wrongClusterId = (BigInt(TRUSTED_CLUSTER_ID) ^ 1n).toString();
  const wrongClusterDoBlock = buildClusterVerificationDoBlock(wrongClusterId);
  const hostileAttempt = [
    wrongClusterDoBlock,
    "CREATE TABLE __r19_1_should_not_exist (id int);",
  ].join("\n");
  const r = spawnSync(
    "psql",
    ["-t", "-A", "-v", "ON_ERROR_STOP=1", "-1", "-c", hostileAttempt],
    { env: superEnv, encoding: "utf8", maxBuffer: 10 * 1024 * 1024, timeout: 10_000 }
  );
  assertTrue(r.status !== 0, "psql should fail on cluster mismatch");
  assertContains(String(r.stderr).toLowerCase(), "cluster mismatch", "stderr should mention cluster mismatch");
  const after = captureTargetState(superEnv);
  assertEq(after, targetStateBeforeCleanup, "state unchanged — no DDL ran");
});

// ── Cleanup (as superuser) ──────────────────────────────────────────────
// R18-1: cleanup also fails-closed through the same guarded pattern as
// setup. DB name DO block + DROP statements combined in a single psql -1
// -v ON_ERROR_STOP=1 transaction. On marker mismatch the transaction
// aborts before any DROP statement runs — closing the R17 cleanup gap.
const cleanupDbNameDoBlock = buildDbNameVerificationDoBlock(EXPECTED_DB_NAME);
const cleanupClusterDoBlock = buildClusterVerificationDoBlock(TRUSTED_CLUSTER_ID);
const cleanupSql = [
  cleanupDbNameDoBlock,
  cleanupClusterDoBlock,
  `DROP TABLE IF EXISTS ${TEST_TABLE};`,
  `DROP ROLE IF EXISTS ${ROLE_NAME};`,
].join("\n");
const cleanupResult = spawnSync(
  "psql",
  ["-t", "-A", "-F", "\t", "-v", "ON_ERROR_STOP=1", "-1", "-c", cleanupSql],
  { env: superEnv, encoding: "utf8", maxBuffer: 10 * 1024 * 1024, timeout: 30_000 }
);
if (cleanupResult.status !== 0) {
  console.error("CLEANUP FAILED:");
  console.error(cleanupResult.stderr);
  process.exit(1);
}

console.log(`\n${passed} passed, ${failed} failed\n`);
process.exit(failed > 0 ? 1 : 0);