// Build src/lib/brand-logo.ts from the uploaded PNG.
// Run: node scripts/build-logo-ts.js
const fs = require('fs');
const path = require('path');

const srcPng = '/home/z/my-project/upload/Iconic_Inverted colour.png';
const b64 = fs.readFileSync(srcPng).toString('base64');

const out = [
  '// ============================================================================',
  '// Brand Logo - Valtriox - Embedded base64 of the founder-uploaded icon',
  '// ============================================================================',
  '// This file is AUTO-GENERATED by scripts/build-logo-ts.js.',
  '// Source: /home/z/my-project/upload/Iconic_Inverted colour.png (235x282, RGBA)',
  '//',
  '// The logo is embedded as a base64 data URI so it works on Vercel serverless',
  '// without any filesystem dependency. It is used as the primary brand mark on',
  '// ALL reports, proposals, lead magnets and invoices regardless of which',
  '// organization the document is for - per founder branding directive.',
  '// ============================================================================',
  '',
  '// PNG mime type, base64-encoded payload',
  'export const BRAND_LOGO_DATA_URI = "data:image/png;base64,' + b64 + '";',
  '',
  'let _brandLogoBuffer: Buffer | null | undefined;',
  '',
  '/**',
  ' * Returns the brand logo as a Node Buffer (cached after first call).',
  ' * Returns null only if base64 decoding fails (should never happen).',
  ' */',
  'export function getBrandLogoBuffer(): Buffer | null {',
  '  if (_brandLogoBuffer !== undefined) return _brandLogoBuffer;',
  '  try {',
  '    const b64 = BRAND_LOGO_DATA_URI.split(\',\')[1];',
  '    _brandLogoBuffer = b64 ? Buffer.from(b64, \'base64\') : null;',
  '  } catch {',
  '    _brandLogoBuffer = null;',
  '  }',
  '  return _brandLogoBuffer;',
  '}',
  '',
  '/**',
  ' * Source dimensions of the brand logo PNG (used to preserve aspect ratio).',
  ' * Source: 235 x 282 (aspect ratio 1.2:1, slightly taller than wide).',
  ' */',
  'export const BRAND_LOGO_SOURCE_W = 235;',
  'export const BRAND_LOGO_SOURCE_H = 282;',
  'export const BRAND_LOGO_ASPECT = BRAND_LOGO_SOURCE_H / BRAND_LOGO_SOURCE_W; // ~1.2',
  ''
].join('\n');

fs.writeFileSync(path.join('src', 'lib', 'brand-logo.ts'), out);
console.log('Wrote src/lib/brand-logo.ts', fs.statSync('src/lib/brand-logo.ts').size, 'bytes');
